export interface IrregularVerb {
    base: string;
    past: string;
    participle: string;
    meaning: string;
}

export const irregularVerbs: IrregularVerb[] = [
    { base: "abide", past: "abode/abided", participle: "abode/abided", meaning: "lưu trú, tuân theo" },
    { base: "arise", past: "arose", participle: "arisen", meaning: "phát sinh" },
    { base: "awake", past: "awoke", participle: "awoken", meaning: "đánh thức, thức dậy" },
    { base: "be", past: "was/were", participle: "been", meaning: "thì, là, ở" },
    { base: "bear", past: "bore", participle: "borne", meaning: "mang, chịu đựng" },
    { base: "beat", past: "beat", participle: "beaten", meaning: "đánh" },
    { base: "become", past: "became", participle: "become", meaning: "trở thành" },
    { base: "befall", past: "befell", participle: "befallen", meaning: "xảy đến" },
    { base: "begin", past: "began", participle: "begun", meaning: "bắt đầu" },
    { base: "behold", past: "beheld", participle: "beheld", meaning: "ngắm nhìn" },
    { base: "bend", past: "bent", participle: "bent", meaning: "bẻ cong" },
    { base: "beset", past: "beset", participle: "beset", meaning: "bao quanh" },
    { base: "bespeak", past: "bespoke", participle: "bespoken", meaning: "chứng tỏ" },
    { base: "bid", past: "bid", participle: "bid", meaning: "trả giá" },
    { base: "bind", past: "bound", participle: "bound", meaning: "trói, buộc" },
    { base: "bite", past: "bit", participle: "bitten", meaning: "cắn" },
    { base: "bleed", past: "bled", participle: "bled", meaning: "chảy máu" },
    { base: "blow", past: "blew", participle: "blown", meaning: "thổi" },
    { base: "break", past: "broke", participle: "broken", meaning: "đập vỡ" },
    { base: "breed", past: "bred", participle: "bred", meaning: "nuôi, dạy dỗ" },
    { base: "bring", past: "brought", participle: "brought", meaning: "mang đến" },
    { base: "broadcast", past: "broadcast", participle: "broadcast", meaning: "phát thanh" },
    { base: "build", past: "built", participle: "built", meaning: "xây dựng" },
    { base: "burn", past: "burnt/burned", participle: "burnt/burned", meaning: "đốt, cháy" },
    { base: "burst", past: "burst", participle: "burst", meaning: "nổ tung" },
    { base: "buy", past: "bought", participle: "bought", meaning: "mua" },
    { base: "cast", past: "cast", participle: "cast", meaning: "ném, tung" },
    { base: "catch", past: "caught", participle: "caught", meaning: "bắt, chụp" },
    { base: "chide", past: "chid/chided", participle: "chidden/chided", meaning: "mắng chửi" },
    { base: "choose", past: "chose", participle: "chosen", meaning: "chọn, lựa" },
    { base: "cleave", past: "clove/cleft/cleaved", participle: "cloven/cleft/cleaved", meaning: "chẻ, tách hai" },
    { base: "cling", past: "clung", participle: "clung", meaning: "bám vào" },
    { base: "come", past: "came", participle: "come", meaning: "đến" },
    { base: "cost", past: "cost", participle: "cost", meaning: "có giá là" },
    { base: "creep", past: "crept", participle: "crept", meaning: "bò, trườn" },
    { base: "cut", past: "cut", participle: "cut", meaning: "cắt, chặt" },
    { base: "deal", past: "dealt", participle: "dealt", meaning: "giao thiệp" },
    { base: "dig", past: "dug", participle: "dug", meaning: "đào" },
    { base: "dive", past: "dove/dived", participle: "dived", meaning: "lặn" },
    { base: "do", past: "did", participle: "done", meaning: "làm" },
    { base: "draw", past: "drew", participle: "drawn", meaning: "vẽ, kéo" },
    { base: "dream", past: "dreamt/dreamed", participle: "dreamt/dreamed", meaning: "mơ thấy" },
    { base: "drink", past: "drank", participle: "drunk", meaning: "uống" },
    { base: "drive", past: "drove", participle: "driven", meaning: "lái xe" },
    { base: "dwell", past: "dwelt", participle: "dwelt", meaning: "trú ngụ" },
    { base: "eat", past: "ate", participle: "eaten", meaning: "ăn" },
    { base: "fall", past: "fell", participle: "fallen", meaning: "ngã, rơi" },
    { base: "feed", past: "fed", participle: "fed", meaning: "cho ăn" },
    { base: "feel", past: "felt", participle: "felt", meaning: "cảm thấy" },
    { base: "fight", past: "fought", participle: "fought", meaning: "chiến đấu" },
    { base: "find", past: "found", participle: "found", meaning: "tìm thấy" },
    { base: "flee", past: "fled", participle: "fled", meaning: "chạy trốn" },
    { base: "fling", past: "flung", participle: "flung", meaning: "tung; quăng" },
    { base: "fly", past: "flew", participle: "flown", meaning: "bay" },
    { base: "forbid", past: "forbade/forbad", participle: "forbidden", meaning: "cấm đoán" },
    { base: "forecast", past: "forecast/forecasted", participle: "forecast/forecasted", meaning: "tiên đoán" },
    { base: "forget", past: "forgot", participle: "forgotten", meaning: "quên" },
    { base: "forgive", past: "forgave", participle: "forgiven", meaning: "tha thứ" },
    { base: "forsake", past: "forsook", participle: "forsaken", meaning: "bỏ rơi" },
    { base: "freeze", past: "froze", participle: "frozen", meaning: "đóng băng" },
    { base: "get", past: "got", participle: "got/gotten", meaning: "có được" },
    { base: "give", past: "gave", participle: "given", meaning: "cho" },
    { base: "go", past: "went", participle: "gone", meaning: "đi" },
    { base: "grind", past: "ground", participle: "ground", meaning: "nghiền, xay" },
    { base: "grow", past: "grew", participle: "grown", meaning: "mọc, trồng" },
    { base: "hang", past: "hung", participle: "hung", meaning: "treo" },
    { base: "have", past: "had", participle: "had", meaning: "có" },
    { base: "hear", past: "heard", participle: "heard", meaning: "nghe" },
    { base: "hide", past: "hid", participle: "hidden", meaning: "giấu" },
    { base: "hit", past: "hit", participle: "hit", meaning: "đụng" },
    { base: "hold", past: "held", participle: "held", meaning: "cầm, nắm" },
    { base: "hurt", past: "hurt", participle: "hurt", meaning: "làm đau" },
    { base: "keep", past: "kept", participle: "kept", meaning: "giữ" },
    { base: "kneel", past: "knelt/kneeled", participle: "knelt/kneeled", meaning: "quỳ" },
    { base: "know", past: "knew", participle: "known", meaning: "biết" },
    { base: "lay", past: "laid", participle: "laid", meaning: "đặt, để" },
    { base: "lead", past: "led", participle: "led", meaning: "dẫn dắt" },
    { base: "lean", past: "leant/leaned", participle: "leant/leaned", meaning: "tựa, ngả" },
    { base: "leap", past: "leapt", participle: "leapt", meaning: "nhảy, hăm hở" },
    { base: "learn", past: "learnt/learned", participle: "learnt/learned", meaning: "học" },
    { base: "leave", past: "left", participle: "left", meaning: "ra đi" },
    { base: "lend", past: "lent", participle: "lent", meaning: "cho mượn" },
    { base: "let", past: "let", participle: "let", meaning: "cho phép" },
    { base: "lie", past: "lay", participle: "lain", meaning: "nằm" },
    { base: "light", past: "lit/lighted", participle: "lit/lighted", meaning: "thắp sáng" },
    { base: "lose", past: "lost", participle: "lost", meaning: "mất" },
    { base: "make", past: "made", participle: "made", meaning: "làm" },
    { base: "mean", past: "meant", participle: "meant", meaning: "có nghĩa là" },
    { base: "meet", past: "met", participle: "met", meaning: "gặp mặt" },
    { base: "mow", past: "mowed", participle: "mown/mowed", meaning: "cắt cỏ" },
    { base: "offset", past: "offset", participle: "offset", meaning: "đền bù" },
    { base: "overcome", past: "overcame", participle: "overcome", meaning: "vượt qua" },
    { base: "partake", past: "partook", participle: "partaken", meaning: "tham gia" },
    { base: "pay", past: "paid", participle: "paid", meaning: "trả" },
    { base: "plead", past: "pled/pleaded", participle: "pled/pleaded", meaning: "bào chữa" },
    { base: "prove", past: "proved", participle: "proven/proved", meaning: "chứng minh" },
    { base: "put", past: "put", participle: "put", meaning: "đặt; để" },
    { base: "quit", past: "quit", participle: "quit", meaning: "bỏ" },
    { base: "read", past: "read", participle: "read", meaning: "đọc" },
    { base: "relay", past: "relaid", participle: "relaid", meaning: "truyền âm" },
    { base: "rend", past: "rent", participle: "rent", meaning: "xé, rách" },
    { base: "ride", past: "rode", participle: "ridden", meaning: "cưỡi" },
    { base: "ring", past: "rang", participle: "rung", meaning: "rung chuông" },
    { base: "rise", past: "rose", participle: "risen", meaning: "mọc" },
    { base: "run", past: "ran", participle: "run", meaning: "chạy" },
    { base: "saw", past: "sawed", participle: "sawn", meaning: "cưa" },
    { base: "say", past: "said", participle: "said", meaning: "nói" },
    { base: "see", past: "saw", participle: "seen", meaning: "nhìn thấy" },
    { base: "seek", past: "sought", participle: "sought", meaning: "tìm kiếm" },
    { base: "sell", past: "sold", participle: "sold", meaning: "bán" },
    { base: "send", past: "sent", participle: "sent", meaning: "gửi" },
    { base: "set", past: "set", participle: "set", meaning: "đặt, để" },
    { base: "sew", past: "sewed", participle: "sewn/sewed", meaning: "may" },
    { base: "shake", past: "shook", participle: "shaken", meaning: "rung, lắc" },
    { base: "shed", past: "shed", participle: "shed", meaning: "rơi, rụng" },
    { base: "shine", past: "shone", participle: "shone", meaning: "chiếu sáng" },
    { base: "shoe", past: "shod", participle: "shod", meaning: "đóng móng ngựa" },
    { base: "shoot", past: "shot", participle: "shot", meaning: "bắn" },
    { base: "show", past: "showed", participle: "shown/showed", meaning: "cho xem" },
    { base: "shrink", past: "shrank", participle: "shrunk", meaning: "co rút" },
    { base: "shut", past: "shut", participle: "shut", meaning: "đóng lại" },
    { base: "sing", past: "sang", participle: "sung", meaning: "ca hát" },
    { base: "sink", past: "sank", participle: "sunk", meaning: "chìm/đắm" },
    { base: "sit", past: "sat", participle: "sat", meaning: "ngồi" },
    { base: "slay", past: "slew", participle: "slain", meaning: "sát hại" },
    { base: "sleep", past: "slept", participle: "slept", meaning: "ngủ" },
    { base: "slide", past: "slid", participle: "slid", meaning: "trượt" },
    { base: "sling", past: "slung", participle: "slung", meaning: "ném mạnh" },
    { base: "slit", past: "slit", participle: "slit", meaning: "rạch, khứa" },
    { base: "smell", past: "smelt", participle: "smelt", meaning: "ngửi" },
    { base: "sow", past: "sowed", participle: "sown/sowed", meaning: "gieo" },
    { base: "speak", past: "spoke", participle: "spoken", meaning: "nói" },
    { base: "speed", past: "sped/speeded", participle: "sped/speeded", meaning: "chạy vụt" },
    { base: "spell", past: "spelt/spelled", participle: "spelt/spelled", meaning: "đánh vần" },
    { base: "spend", past: "spent", participle: "spent", meaning: "tiêu xài" },
    { base: "spill", past: "spilt/spilled", participle: "spilt/spilled", meaning: "tràn đổ" },
    { base: "spin", past: "spun/span", participle: "spun", meaning: "quay sợi" },
    { base: "spit", past: "spat", participle: "spat", meaning: "khạc nhổ" },
    { base: "split", past: "split", participle: "split", meaning: "chẻ, nứt" },
    { base: "spoil", past: "spoilt/spoiled", participle: "spoilt/spoiled", meaning: "làm hỏng" },
    { base: "spread", past: "spread", participle: "spread", meaning: "lan truyền" },
    { base: "spring", past: "sprang", participle: "sprung", meaning: "nhảy" },
    { base: "stand", past: "stood", participle: "stood", meaning: "đứng" },
    { base: "steal", past: "stole", participle: "stolen", meaning: "đánh cắp" },
    { base: "stick", past: "stuck", participle: "stuck", meaning: "ghim vào; đính" },
    { base: "sting", past: "stung", participle: "stung", meaning: "châm; chích; đốt" },
    { base: "stink", past: "stunk/stank", participle: "stunk", meaning: "bốc mùi hôi" },
    { base: "stride", past: "strode", participle: "stridden", meaning: "bước sải" },
    { base: "strike", past: "struck", participle: "struck", meaning: "đánh đập" },
    { base: "string", past: "strung", participle: "strung", meaning: "gắn dây" },
    { base: "strive", past: "strove", participle: "striven", meaning: "cố sức" },
    { base: "swear", past: "swore", participle: "sworn", meaning: "tuyên thệ" },
    { base: "sweat", past: "sweat/sweated", participle: "sweat/sweated", meaning: "đổ mồ hôi" },
    { base: "sweep", past: "swept", participle: "swept", meaning: "quét" },
    { base: "swell", past: "swelled", participle: "swollen/swelled", meaning: "phồng; sưng" },
    { base: "swim", past: "swam", participle: "swum", meaning: "bơi" },
    { base: "swing", past: "swung", participle: "swung", meaning: "đong đưa" },
    { base: "take", past: "took", participle: "taken", meaning: "cầm, lấy" },
    { base: "teach", past: "taught", participle: "taught", meaning: "dạy" },
    { base: "tear", past: "tore", participle: "torn", meaning: "xé" },
    { base: "tell", past: "told", participle: "told", meaning: "kể" },
    { base: "think", past: "thought", participle: "thought", meaning: "suy nghĩ" },
    { base: "thrive", past: "throve/thrived", participle: "thriven/thrived", meaning: "thịnh vượng" },
    { base: "throw", past: "threw", participle: "thrown", meaning: "ném" },
    { base: "thrust", past: "thrust", participle: "thrust", meaning: "thọc; nhấn" },
    { base: "tread", past: "trod", participle: "trodden/trod", meaning: "giẫm, đạp" },
    { base: "undergo", past: "underwent", participle: "undergone", meaning: "trải qua" },
    { base: "understand", past: "understood", participle: "understood", meaning: "hiểu" },
    { base: "undertake", past: "undertook", participle: "undertaken", meaning: "đảm nhận" },
    { base: "upset", past: "upset", participle: "upset", meaning: "làm đổ" },
    { base: "wake", past: "woke", participle: "woken", meaning: "thức giấc" },
    { base: "wear", past: "wore", participle: "worn", meaning: "mặc" },
    { base: "weave", past: "wove", participle: "woven", meaning: "dệt" },
    { base: "weep", past: "wept", participle: "wept", meaning: "khóc" },
    { base: "wet", past: "wet/wetted", participle: "wet/wetted", meaning: "làm ướt" },
    { base: "win", past: "won", participle: "won", meaning: "chiến thắng" },
    { base: "wind", past: "wound", participle: "wound", meaning: "quấn" },
    { base: "withdraw", past: "withdrew", participle: "withdrawn", meaning: "rút lui" },
    { base: "wring", past: "wrung", participle: "wrung", meaning: "vặn; siết chặt" },
    { base: "write", past: "wrote", participle: "written", meaning: "viết" },
];
