type CEFRLevel = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export interface Question {
	sentence: string; // sentence with a blank '____'
	options: string[]; // length 4
	correct: number; // 0-3
	explanation: string; // short Vietnamese explanation
}

// Prompt to generate quiz questions. Follow exactly when producing questions.
export const quizPrompt = `
Bạn là giáo viên tiếng Anh theo khung CEFR.

Hãy tạo bộ câu hỏi trắc nghiệm tiếng Anh từ trình độ A1 đến C2.

YÊU CẦU CHUNG (BẮT BUỘC):
- Mỗi level (A1, A2, B1, B2, C1, C2) có CHÍNH XÁC 100 câu
- Tổng cộng 600 câu
- TẤT CẢ câu hỏi phải KHÁC NHAU (không lặp sentence, không lặp ngữ cảnh)
- Không dùng template lặp kiểu (Q{n}), không dùng biến giả
- Mỗi câu gồm:
	- sentence: câu tiếng Anh có chỗ trống "____"
	- options: 4 đáp án khác nhau
	- correct: index (0–3) của đáp án đúng
	- explanation: giải thích ngắn gọn bằng tiếng Việt
- Không dùng từ vựng vượt trình độ
- Không lặp đáp án trong cùng một câu

PHÂN BỔ ĐỘ KHÓ:
- A1: present simple, present continuous, basic prepositions
- A2: past simple, future (will / going to), conditional type 1, comparatives
- B1: present perfect, past perfect (cơ bản), reported speech
- B2: mixed tenses, passive, conditional type 2 & 3
- C1: inversion, advanced conditionals, complex clauses
- C2: advanced inversion, perfect passive, hypothetical structures

OUTPUT FORMAT (TypeScript, KHÔNG markdown, KHÔNG giải thích ngoài code):

export const questions: Record<CEFRLevel, Question[]> = {
	A1: [ /* 100 Question objects */ ],
	A2: [ /* 100 Question objects */ ],
	B1: [ /* 100 Question objects */ ],
	B2: [ /* 100 Question objects */ ],
	C1: [ /* 100 Question objects */ ],
	C2: [ /* 100 Question objects */ ],
};

Trước khi trả lời, hãy kiểm tra để đảm bảo:
- Mỗi level đủ 100 câu
- Không có câu nào trùng sentence hoặc cấu trúc + ngữ cảnh
`;

export const questions: Record<CEFRLevel, Question[]> = {
	A1: [
		{ sentence: "She ____ to school every day.", options: ["go", "goes", "going", "gone"], correct: 1, explanation: "Hiện tại đơn với chủ ngữ ngôi thứ 3 số ít 'She' chia động từ thêm 'es'." },
		{ sentence: "I ____ a student.", options: ["is", "are", "am", "be"], correct: 2, explanation: "Động từ to be đi với chủ ngữ 'I' là 'am'." },
		{ sentence: "They ____ playing football now.", options: ["is", "am", "are", "be"], correct: 2, explanation: "Hiện tại tiếp diễn: S + am/is/are + V-ing. Chủ ngữ 'They' đi với 'are'." },
		{ sentence: "The book is ____ the table.", options: ["in", "on", "at", "to"], correct: 1, explanation: "Giới từ chỉ vị trí: 'on the table' (trên bàn)." },
		{ sentence: "He ____ breakfast at 7 AM.", options: ["eat", "eats", "eating", "ate"], correct: 1, explanation: "Hiện tại đơn với thói quen hàng ngày, 'He' thêm 's'." },
		{ sentence: "Listen! The bird ____.", options: ["sing", "sings", "is singing", "sang"], correct: 2, explanation: "Dấu hiệu 'Listen!' dùng thì hiện tại tiếp diễn." },
		{ sentence: "We ____ from Vietnam.", options: ["is", "am", "are", "be"], correct: 2, explanation: "'We' đi với động từ to be 'are'." },
		{ sentence: "Do you ____ coffee?", options: ["like", "likes", "liking", "liked"], correct: 0, explanation: "Câu hỏi thì hiện tại đơn: Do/Does + S + V nguyên thể." },
		{ sentence: "My father ____ a doctor.", options: ["is", "am", "are", "be"], correct: 0, explanation: "'My father' là ngôi thứ 3 số ít, dùng 'is'." },
		{ sentence: "Where ____ she live?", options: ["do", "does", "is", "are"], correct: 1, explanation: "Câu hỏi Wh- với động từ thường ở hiện tại đơn: Where + does + S + V?" },
		{ sentence: "Look! It ____.", options: ["rain", "rains", "is raining", "rained"], correct: 2, explanation: "Dấu hiệu 'Look!' dùng thì hiện tại tiếp diễn." },
		{ sentence: "I usually ____ up at 6 o'clock.", options: ["get", "gets", "getting", "got"], correct: 0, explanation: "Trạng từ 'usually' dùng thì hiện tại đơn, 'I' + V nguyên thể." },
		{ sentence: "The cat is ____ the box.", options: ["in", "on", "at", "to"], correct: 0, explanation: "'in the box' (trong hộp)." },
		{ sentence: "They ____ not happy.", options: ["is", "am", "are", "be"], correct: 2, explanation: "Phủ định to be: S + am/is/are + not." },
		{ sentence: "____ is your name?", options: ["What", "Where", "When", "Who"], correct: 0, explanation: "Hỏi tên dùng 'What'." },
		{ sentence: "There ____ two apples on the desk.", options: ["is", "am", "are", "be"], correct: 2, explanation: "Cấu trúc There is/There are. 'two apples' là số nhiều dùng 'are'." },
		{ sentence: "He ____ like apples.", options: ["don't", "doesn't", "isn't", "aren't"], correct: 1, explanation: "Phủ định thì hiện tại đơn với động từ thường: S + don't/doesn't + V." },
		{ sentence: "She always ____ her homework.", options: ["do", "does", "doing", "did"], correct: 1, explanation: "Hiện tại đơn với 'always', 'She' đi với 'does'." },
		{ sentence: "I am ____ a letter.", options: ["write", "writes", "writing", "wrote"], correct: 2, explanation: "Hiện tại tiếp diễn: S + am + V-ing." },
		{ sentence: "Are you ____ TV?", options: ["watch", "watches", "watching", "watched"], correct: 2, explanation: "Câu hỏi hiện tại tiếp diễn: Are you + V-ing?" },
		{ sentence: "We go to school ____ bus.", options: ["in", "on", "by", "at"], correct: 2, explanation: "Phương tiện đi lại dùng giới từ 'by'." },
		{ sentence: "The picture is ____ the wall.", options: ["in", "on", "at", "under"], correct: 1, explanation: "'on the wall' (trên tường)." },
		{ sentence: "____ old are you?", options: ["What", "How", "Who", "Where"], correct: 1, explanation: "Hỏi tuổi dùng 'How old'." },
		{ sentence: "My brother ____ tall.", options: ["is", "am", "are", "have"], correct: 0, explanation: "Miêu tả đặc điểm dùng to be 'is'." },
		{ sentence: "They ____ English very well.", options: ["speak", "speaks", "speaking", "spoke"], correct: 0, explanation: "Hiện tại đơn, 'They' + V nguyên thể." },
		{ sentence: "Is she ____ student?", options: ["a", "an", "the", "-"], correct: 0, explanation: "Mạo từ 'a' trước danh từ đếm được số ít bắt đầu bằng phụ âm." },
		{ sentence: "Please ____ the door.", options: ["open", "opens", "opening", "opened"], correct: 0, explanation: "Câu mệnh lệnh bắt đầu bằng động từ nguyên thể." },
		{ sentence: "I have an apple ____ a banana.", options: ["and", "but", "so", "or"], correct: 0, explanation: "Liên từ 'and' để nối hai danh từ tương đương." },
		{ sentence: "She is ____ beautiful girl.", options: ["a", "an", "the", "-"], correct: 0, explanation: "Cụm danh từ: a + adj + noun." },
		{ sentence: "What time ____ it?", options: ["is", "am", "are", "be"], correct: 0, explanation: "Hỏi giờ: What time is it?" },
		{ sentence: "They are ____ the garden.", options: ["in", "on", "at", "to"], correct: 0, explanation: "'in the garden' (trong vườn)." },
		{ sentence: "He ____ play the guitar.", options: ["can", "cans", "canning", "to can"], correct: 0, explanation: "Động từ khuyết thiếu 'can' + V nguyên thể." },
		{ sentence: "I ____ thirsty.", options: ["is", "am", "are", "have"], correct: 1, explanation: "Diễn tả cảm giác dùng to be, 'I' đi với 'am'." },
		{ sentence: "Do they ____ here?", options: ["live", "lives", "living", "lived"], correct: 0, explanation: "Câu hỏi Do + S + V nguyên thể?" },
		{ sentence: "This is ____ pen.", options: ["my", "I", "me", "mine"], correct: 0, explanation: "Tính từ sở hữu 'my' đứng trước danh từ." },
		{ sentence: "____ do you live?", options: ["Where", "What", "Who", "When"], correct: 0, explanation: "Hỏi địa điểm dùng 'Where'." },
		{ sentence: "He is sitting ____ me.", options: ["next to", "next", "between", "in"], correct: 0, explanation: "Giới từ 'next to' (bên cạnh)." },
		{ sentence: "My mother is a nurse. ____ is kind.", options: ["He", "She", "It", "They"], correct: 1, explanation: "Đại từ thay thế cho 'My mother' là 'She'." },
		{ sentence: "There ____ many people in the room.", options: ["is", "are", "am", "be"], correct: 1, explanation: "'many people' là số nhiều, dùng 'are'." },
		{ sentence: "I ____ not like fast food.", options: ["do", "does", "is", "are"], correct: 0, explanation: "Phủ định hiện tại đơn với động từ thường, chủ ngữ 'I' dùng 'do not'." },
		{ sentence: "The sun ____ in the East.", options: ["rise", "rises", "rising", "rose"], correct: 1, explanation: "Sự thật hiển nhiên: Mặt trời mọc ở đằng Đông, dùng thì hiện tại đơn." },
		{ sentence: "Can you ____ me?", options: ["help", "helps", "helping", "helped"], correct: 0, explanation: "Sau 'Can' là động từ nguyên thể." },
		{ sentence: "We are ____ dinner.", options: ["have", "has", "having", "had"], correct: 2, explanation: "Hiện tại tiếp diễn: We are having dinner." },
		{ sentence: "____ is that man?", options: ["Who", "What", "Where", "When"], correct: 0, explanation: "Hỏi người dùng 'Who'." },
		{ sentence: "I go to work ____ 8 AM.", options: ["in", "on", "at", "to"], correct: 2, explanation: "Giới từ chỉ giờ dùng 'at'." },
		{ sentence: "She ____ got long hair.", options: ["have", "has", "is", "are"], correct: 1, explanation: "Cấu trúc 'have/has got', 'She' dùng 'has'." },
		{ sentence: "The dog is sleeping ____ the table.", options: ["under", "in", "on", "between"], correct: 0, explanation: "'under the table' (dưới gầm bàn)." },
		{ sentence: "How ____ rice do you want?", options: ["much", "many", "some", "any"], correct: 0, explanation: "'Rice' là danh từ không đếm được, dùng 'How much'." },
		{ sentence: "I ____ TV every evening.", options: ["watch", "watches", "watching", "watched"], correct: 0, explanation: "Thói quen hàng ngày, thì hiện tại đơn." },
		{ sentence: "This car is ____.", options: ["blue", "a blue", "the blue", "blues"], correct: 0, explanation: "Tính từ chỉ màu sắc." },
		{ sentence: "____ cigarettes are bad for you.", options: ["The", "A", "An", "-"], correct: 3, explanation: "Danh từ số nhiều nói chung không cần mạo từ." },
		{ sentence: "He is ____ best student.", options: ["the", "a", "an", "-"], correct: 0, explanation: "So sánh nhất dùng mạo từ 'the'." },
		{ sentence: "They ____ to the radio now.", options: ["listen", "listens", "are listening", "listening"], correct: 2, explanation: "Dấu hiệu 'now' dùng thì hiện tại tiếp diễn." },
		{ sentence: "My house is ____ the school.", options: ["near", "next", "between", "on"], correct: 0, explanation: "Giới từ 'near' (gần)." },
		{ sentence: "I want ____ buy a new phone.", options: ["to", "for", "at", "in"], correct: 0, explanation: "Cấu trúc 'want to V'." },
		{ sentence: "She ____ not at home yesterday.", options: ["was", "were", "is", "are"], correct: 0, explanation: "Quá khứ của to be với 'She' là 'was'." },
		{ sentence: "____ you speak English?", options: ["Do", "Does", "Are", "Is"], correct: 0, explanation: "Câu hỏi khả năng/thói quen dùng 'Do'." },
		{ sentence: "The children ____ playing in the park.", options: ["is", "am", "are", "be"], correct: 2, explanation: "'The children' là số nhiều, dùng 'are'." },
		{ sentence: "I often ____ my grandparents on Sundays.", options: ["visit", "visits", "visiting", "visited"], correct: 0, explanation: "Thói quen thường xuyên 'often', dùng hiện tại đơn." },
		{ sentence: "It is a ____ day.", options: ["sun", "sunny", "sunshine", "sunning"], correct: 1, explanation: "Tính từ đứng trước danh từ: 'sunny day'." },
		{ sentence: "____ apple a day keeps the doctor away.", options: ["A", "An", "The", "-"], correct: 1, explanation: "'Apple' bắt đầu bằng nguyên âm, dùng 'An'." },
		{ sentence: "Where ____ your parents?", options: ["is", "am", "are", "be"], correct: 2, explanation: "'Your parents' là số nhiều, dùng 'are'." },
		{ sentence: "He is ____ than me.", options: ["taller", "tall", "tallest", "more tall"], correct: 0, explanation: "So sánh hơn của tính từ ngắn 'tall' là 'taller'." },
		{ sentence: "Do you have ____ money?", options: ["some", "any", "a", "an"], correct: 1, explanation: "Câu nghi vấn dùng 'any'." },
		{ sentence: "I prefer tea ____ coffee.", options: ["to", "than", "from", "with"], correct: 0, explanation: "Cấu trúc 'prefer ... to ...'." },
		{ sentence: "She ____ works on Saturday.", options: ["never", "never doesn't", "don't never", "doesn't never"], correct: 0, explanation: "Trạng từ tần suất 'never' đứng trước động từ thường." },
		{ sentence: "The film was ____.", options: ["bored", "boring", "bores", "bore"], correct: 1, explanation: "Tính từ đuôi -ing chỉ tính chất của sự vật/sự việc." },
		{ sentence: "I can't find my keys. I lost ____.", options: ["they", "their", "them", "it"], correct: 2, explanation: "'Keys' số nhiều, tân ngữ là 'them'." },
		{ sentence: "____ is the weather like?", options: ["What", "How", "Why", "Who"], correct: 0, explanation: "Câu hỏi thời tiết: What is the weather like?" },
		{ sentence: "We ____ dinner when he arrived.", options: ["were having", "had", "have", "are having"], correct: 0, explanation: "Hành động đang xảy ra (quá khứ tiếp diễn) thì hành động khác xen vào." },
		{ sentence: "They ____ arrived yet.", options: ["haven't", "hasn't", "didn't", "don't"], correct: 0, explanation: "Thì hiện tại hoàn thành với 'yet'." },
		{ sentence: "This is the ____ building in the city.", options: ["oldest", "older", "old", "more old"], correct: 0, explanation: "So sánh nhất tính từ ngắn." },
		{ sentence: "I have known him ____ 2010.", options: ["since", "for", "in", "at"], correct: 0, explanation: "Mốc thời gian trong hiện tại hoàn thành dùng 'since'." },
		{ sentence: "If it rains, I ____ at home.", options: ["will stay", "stayed", "would stay", "stay"], correct: 0, explanation: "Câu điều kiện loại 1: If + HTĐ, TLĐ." },
		{ sentence: "He drives very ____.", options: ["careful", "carefully", "care", "caring"], correct: 1, explanation: "Trạng từ bổ nghĩa cho động từ 'drives'." },
		{ sentence: "I ____ to London last year.", options: ["go", "went", "gone", "going"], correct: 1, explanation: "'last year' dùng thì quá khứ đơn." },
		{ sentence: "She is good ____ Math.", options: ["at", "in", "on", "for"], correct: 0, explanation: "Cấu trúc 'good at' (giỏi về)." },
		{ sentence: "____ you like a cup of tea?", options: ["Do", "Would", "Are", "Will"], correct: 1, explanation: "Lời mời lịch sự 'Would you like...'." },
		{ sentence: "The baby is ____.", options: ["crying", "cry", "cries", "cried"], correct: 0, explanation: "Hiện tại tiếp diễn: is crying." },
		{ sentence: "I don't have ____ friends here.", options: ["many", "much", "some", "a"], correct: 0, explanation: "'Friends' đếm được số nhiều, câu phủ định dùng 'many'." },
		{ sentence: "He went to the shop ____ milk.", options: ["to buy", "for buy", "buying", "buy"], correct: 0, explanation: "Chỉ mục đích: to + V." },
		{ sentence: "____ bag is this?", options: ["Whose", "Who", "Whom", "Who's"], correct: 0, explanation: "Hỏi về sở hữu: Whose." },
		{ sentence: "I am interested ____ music.", options: ["in", "on", "at", "with"], correct: 0, explanation: "Cấu trúc 'interested in' (quan tâm đến)." },
		{ sentence: "That is ____ interesting book.", options: ["an", "a", "the", "-"], correct: 0, explanation: "'Interesting' bắt đầu bằng nguyên âm, dùng 'an'." },
		{ sentence: "They ____ football yesterday.", options: ["played", "play", "playing", "plays"], correct: 0, explanation: "'Yesterday' dùng quá khứ đơn." },
		{ sentence: "She runs ____ than me.", options: ["faster", "fast", "fastest", "more fast"], correct: 0, explanation: "So sánh hơn của trạng từ/tính từ ngắn 'fast'." },
		{ sentence: "I ____ my homework already.", options: ["have done", "did", "do", "doing"], correct: 0, explanation: "Hiện tại hoàn thành với 'already'." },
		{ sentence: "____ go to the cinema tonight.", options: ["Let's", "How about", "Why don't", "Shall"], correct: 0, explanation: "Lời rủ rê 'Let's + V'." },
		{ sentence: "He is ____ tired to work.", options: ["too", "so", "very", "enough"], correct: 0, explanation: "Cấu trúc 'too ... to' (quá ... để làm gì)." },
		{ sentence: "This shirt is not big ____ for me.", options: ["enough", "too", "so", "very"], correct: 0, explanation: "Cấu trúc 'adj + enough'." },
		{ sentence: "I saw him ____ the morning.", options: ["in", "on", "at", "by"], correct: 0, explanation: "Buổi trong ngày dùng 'in'." },
		{ sentence: "____ Sunday, I stay home.", options: ["On", "In", "At", "By"], correct: 0, explanation: "Thứ trong tuần dùng 'On'." },
		{ sentence: "What are you ____?", options: ["doing", "do", "did", "done"], correct: 0, explanation: "Hiện tại tiếp diễn: What are you doing?" },
		{ sentence: "My sister is ____ than me.", options: ["younger", "young", "youngest", "more young"], correct: 0, explanation: "So sánh hơn tính từ ngắn." },
		{ sentence: "We ____ to the beach next week.", options: ["are going", "go", "went", "gone"], correct: 0, explanation: "'Next week' dùng tương lai gần (be going to) hoặc HTTD diễn tả tương lai." },
		{ sentence: "He ____ up smoking last year.", options: ["gave", "give", "giving", "given"], correct: 0, explanation: "Cụm từ 'give up' (từ bỏ), quá khứ đơn." },
		{ sentence: "I look forward ____ you.", options: ["to seeing", "to see", "seeing", "see"], correct: 0, explanation: "Cấu trúc 'look forward to V-ing'." },
		{ sentence: "This is the man ____ helped me.", options: ["who", "which", "whom", "whose"], correct: 0, explanation: "Mệnh đề quan hệ chỉ người làm chủ ngữ dùng 'who'." },
		{ sentence: "I enjoy ____ books.", options: ["reading", "read", "to read", "reads"], correct: 0, explanation: "Sau 'enjoy' là V-ing." },
		{ sentence: "It's ____ expensive car.", options: ["an", "a", "the", "-"], correct: 0, explanation: "'Expensive' bắt đầu bằng nguyên âm." },
	],
	A2: [
		{ sentence: "I ____ to the cinema last night.", options: ["go", "went", "gone", "going"], correct: 1, explanation: "Quá khứ đơn của 'go' là 'went', dấu hiệu 'last night'." },
		{ sentence: "She ____ not watch TV yesterday.", options: ["did", "do", "does", "was"], correct: 0, explanation: "Phủ định quá khứ đơn: did not + V." },
		{ sentence: "We ____ flying to Paris tomorrow.", options: ["are", "is", "will", "do"], correct: 0, explanation: "Tương lai gần/HTTD diễn tả kế hoạch: are flying." },
		{ sentence: "If it ____, I will stay at home.", options: ["rains", "rain", "raining", "rained"], correct: 0, explanation: "Câu điều kiện loại 1: If + HTĐ (rains), TLĐ." },
		{ sentence: "He is ____ than his brother.", options: ["taller", "tall", "tallest", "more tall"], correct: 0, explanation: "So sánh hơn tính từ ngắn 'tall'." },
		{ sentence: "This book is ____ than that one.", options: ["more interesting", "interestinger", "most interesting", "interesting"], correct: 0, explanation: "So sánh hơn tính từ dài 'more + adj'." },
		{ sentence: "What ____ you do last weekend?", options: ["did", "do", "does", "were"], correct: 0, explanation: "Câu hỏi quá khứ đơn: What did + S + V?" },
		{ sentence: "I ____ visit my aunt next week.", options: ["will", "am", "going to", "did"], correct: 0, explanation: "Tương lai đơn 'will' diễn tả ý định/quyết định." },
		{ sentence: "They ____ going to buy a new car.", options: ["are", "is", "am", "will"], correct: 0, explanation: "Cấu trúc tương lai gần: be ('are') going to." },
		{ sentence: "If you ____ hard, you will pass the exam.", options: ["study", "studies", "studied", "studying"], correct: 0, explanation: "Điều kiện loại 1: If + S + V(hiện tại)." },
		{ sentence: "My car is ____ than yours.", options: ["faster", "fast", "fastest", "more fast"], correct: 0, explanation: "So sánh hơn tính từ ngắn 'fast'." },
		{ sentence: "Who is the ____ person in your family?", options: ["oldest", "older", "old", "eldest"], correct: 0, explanation: "So sánh nhất tính từ ngắn 'old'." },
		{ sentence: "I ____ breakfast when the phone rang.", options: ["was having", "had", "have", "am having"], correct: 0, explanation: "Qktd (was having) bị Qkđ (rang) xen vào." },
		{ sentence: "We ____ in London for 5 years.", options: ["lived", "live", "living", "lives"], correct: 0, explanation: "Kể lại sự kiện trong quá khứ (hoặc nếu vẫn sống thì dùng perfect, ở đây A2 often uses past for finished time or simple perfect context, but 'lived' is safe narration)." },
		{ sentence: "Did you ____ the game?", options: ["win", "won", "winning", "wins"], correct: 0, explanation: "Sau trợ động từ 'Did', động từ về nguyên mẫu." },
		{ sentence: "I think it ____ rain later.", options: ["will", "is", "going to", "does"], correct: 0, explanation: "Dự đoán tương lai không có căn cứ rõ ràng dùng 'will'." },
		{ sentence: "Look at those clouds! It ____ rain.", options: ["is going to", "will", "shall", "does"], correct: 0, explanation: "Dự đoán có căn cứ dùng 'is going to'." },
		{ sentence: "She is the ____ girl in the class.", options: ["most beautiful", "more beautiful", "beautifullest", "beautiful"], correct: 0, explanation: "So sánh nhất tính từ dài 'the most + adj'." },
		{ sentence: "If I have time, I ____ you.", options: ["will help", "help", "helped", "would help"], correct: 0, explanation: "Điều kiện loại 1." },
		{ sentence: "My bag is ____ heavy as yours.", options: ["as", "so", "than", "more"], correct: 0, explanation: "So sánh bằng 'as ... as'." },
		{ sentence: "____ you go to the party?", options: ["Did", "Do", "Does", "Were"], correct: 0, explanation: "Hỏi về quá khứ (nếu có ngữ cảnh) hoặc thói quen. Ở đây 'Did' là lựa chọn phổ biến cho câu hỏi sự kiện." },
		{ sentence: "I ____ a ghost last night.", options: ["saw", "see", "seen", "seeing"], correct: 0, explanation: "Quá khứ đơn của 'see' là 'saw'." },
		{ sentence: "While I ____, my mom was cooking.", options: ["was reading", "read", "reading", "am reading"], correct: 0, explanation: "Hai hành động song song trong quá khứ: was reading." },
		{ sentence: "He ____ be a doctor one day.", options: ["will", "is", "going", "did"], correct: 0, explanation: "Tương lai đơn 'will'." },
		{ sentence: "Is Paris ____ than London?", options: ["bigger", "big", "biggest", "more big"], correct: 0, explanation: "So sánh hơn 'bigger'." },
		{ sentence: "She plays tennis ____ than me.", options: ["better", "good", "well", "best"], correct: 0, explanation: "So sánh hơn của trạng từ 'well' là 'better'." },
		{ sentence: "If you ____ invite him, he won't come.", options: ["don't", "won't", "didn't", "doesn't"], correct: 0, explanation: "Phủ định trong mệnh đề If loại 1: don't + V." },
		{ sentence: "I remember ____ the door.", options: ["locking", "lock", "to lock", "locked"], correct: 0, explanation: "'Remember V-ing': nhớ đã làm gì." },
		{ sentence: "He stopped ____ because he was tired.", options: ["working", "to work", "work", "worked"], correct: 0, explanation: "Stop + V-ing: dừng việc đang làm lại." },
		{ sentence: "He stopped to ____ water.", options: ["buy", "buying", "bought", "buys"], correct: 0, explanation: "'Stop to V': dừng lại để làm gì." },
		{ sentence: "I enjoy ____ with my friends.", options: ["hanging out", "hang out", "to hang out", "hung out"], correct: 0, explanation: "Enjoy + V-ing." },
		{ sentence: "We decided ____ a new TV.", options: ["to buy", "buying", "buy", "bought"], correct: 0, explanation: "Decide + to V." },
		{ sentence: "She ____ her leg yesterday.", options: ["broke", "break", "breaking", "broken"], correct: 0, explanation: "Quá khứ đơn 'broke'." },
		{ sentence: "When I was young, I ____ swim well.", options: ["could", "can", "may", "might"], correct: 0, explanation: "Khả năng trong quá khứ dùng 'could'." },
		{ sentence: "You ____ smoke here.", options: ["mustn't", "don't have to", "needn't", "couldn't"], correct: 0, explanation: "Cấm đoán dùng 'mustn't'." },
		{ sentence: "I have to ____ up early tomorrow.", options: ["get", "gets", "getting", "got"], correct: 0, explanation: "Sau 'have to' dùng V nguyên thể." },
		{ sentence: "This soup tastes ____.", options: ["good", "well", "badly", "nicely"], correct: 0, explanation: "Động từ chỉ giác quan 'taste' + tính từ." },
		{ sentence: "I'm looking for a place ____ I can relax.", options: ["where", "which", "who", "when"], correct: 0, explanation: "Trạng từ quan hệ chỉ nơi chốn 'where'." },
		{ sentence: "The man ____ car was stolen called the police.", options: ["whose", "who", "which", "whom"], correct: 0, explanation: "Đại từ quan hệ chỉ sở hữu 'whose'." },
		{ sentence: "I ____ never been to Japan.", options: ["have", "has", "did", "was"], correct: 0, explanation: "Hiện tại hoàn thành: have + V3." },
		{ sentence: "Have you ever ____ sushi?", options: ["eaten", "ate", "eat", "eating"], correct: 0, explanation: "Hiện tại hoàn thành: eaten." },
		{ sentence: "She has lived here ____ 2015.", options: ["since", "for", "in", "ago"], correct: 0, explanation: "Mốc thời gian dùng 'since'." },
		{ sentence: "We have worked here ____ ten years.", options: ["for", "since", "during", "in"], correct: 0, explanation: "Khoảng thời gian dùng 'for'." },
		{ sentence: "They ____ just finished their homework.", options: ["have", "did", "are", "had"], correct: 0, explanation: "Hiện tại hoàn thành với 'just'." },
		{ sentence: "I was born ____ 1999.", options: ["in", "on", "at", "during"], correct: 0, explanation: "Năm dùng giới từ 'in'." },
		{ sentence: "____ you help me carry this box?", options: ["Could", "Do", "Are", "Have"], correct: 0, explanation: "Yêu cầu lịch sự dùng 'Could'." },
		{ sentence: "If she ____, tell her I'm out.", options: ["calls", "call", "calling", "called"], correct: 0, explanation: "Điều kiện loại 1 (mệnh lệnh)." },
		{ sentence: "It's the ____ film I've ever seen.", options: ["best", "good", "better", "well"], correct: 0, explanation: "So sánh nhất 'the best'." },
		{ sentence: "He is interested ____ learning English.", options: ["in", "on", "at", "about"], correct: 0, explanation: "Interested in." },
		{ sentence: "I am bored ____ this game.", options: ["with", "about", "of", "in"], correct: 0, explanation: "Bored with." },
		{ sentence: "My phone is similar ____ yours.", options: ["to", "with", "as", "from"], correct: 0, explanation: "Similar to." },
		{ sentence: "Different ____ me, he likes coffee.", options: ["from", "to", "with", "than"], correct: 0, explanation: "Different from." },
		{ sentence: "I'm afraid ____ spiders.", options: ["of", "in", "at", "on"], correct: 0, explanation: "Afraid of." },
		{ sentence: "She is good ____ cooking.", options: ["at", "in", "on", "for"], correct: 0, explanation: "Good at." },
		{ sentence: "He asked me ____ help him.", options: ["to", "for", "that", "if"], correct: 0, explanation: "Ask someone to V." },
		{ sentence: "I told him ____ wait.", options: ["to", "for", "that", "if"], correct: 0, explanation: "Tell someone to V." },
		{ sentence: "He said that he ____ busy.", options: ["was", "is", "were", "been"], correct: 0, explanation: "Câu tường thuật lùi thì: is -> was." },
		{ sentence: "She told me she ____ travel the following week.", options: ["would", "will", "can", "may"], correct: 0, explanation: "Tường thuật: will -> would." },
		{ sentence: "Do you know where ____?", options: ["he is", "is he", "he be", "does he be"], correct: 0, explanation: "Câu hỏi gián tiếp: từ để hỏi + S + V." },
		{ sentence: "I wonder why ____ crying.", options: ["she is", "is she", "does she", "she does"], correct: 0, explanation: "Câu hỏi gián tiếp: why + S + V." },
		{ sentence: "My shoes are dirty. I need to clean ____.", options: ["them", "it", "they", "their"], correct: 0, explanation: "'Shoes' số nhiều -> them." },
		{ sentence: "Give ____ the book, please.", options: ["me", "my", "I", "mine"], correct: 0, explanation: "Tân ngữ 'me'." },
		{ sentence: "This house was ____ in 1990.", options: ["built", "build", "building", "builder"], correct: 0, explanation: "Bị động quá khứ đơn: was built." },
		{ sentence: "The letter ____ sent yesterday.", options: ["was", "is", "were", "are"], correct: 0, explanation: "Bị động quá khứ đơn (số ít)." },
		{ sentence: "English ____ spoken all over the world.", options: ["is", "are", "was", "were"], correct: 0, explanation: "Bị động hiện tại đơn." },
		{ sentence: "I used ____ play football when I was young.", options: ["to", "for", "in", "at"], correct: 0, explanation: "Cấu trúc 'used to V' chỉ thói quen trong quá khứ." },
		{ sentence: "Didn't you ____ to like tomatoes?", options: ["use", "used", "using", "uses"], correct: 0, explanation: "Trong câu hỏi/phủ định của 'used to', 'use' về nguyên mẫu." },
		{ sentence: "It's time we ____ home.", options: ["went", "go", "gone", "going"], correct: 0, explanation: "It's time + S + V(quá khứ giả định)." },
		{ sentence: "I wish I ____ a rich man.", options: ["were", "am", "was", "be"], correct: 0, explanation: "Câu ước loại 2 (ngược hiện tại): were (cho mọi ngôi)." },
		{ sentence: "If only I ____ the answer.", options: ["knew", "know", "known", "knowing"], correct: 0, explanation: "If only + V(quá khứ)." },
		{ sentence: "He acts as if he ____ the boss.", options: ["were", "is", "was", "be"], correct: 0, explanation: "As if + V(quá khứ)." },
		{ sentence: "Would you mind ____ the window?", options: ["opening", "open", "to open", "opened"], correct: 0, explanation: "Would you mind + V-ing." },
		{ sentence: "It's no use ____ to him.", options: ["talking", "talk", "to talk", "talked"], correct: 0, explanation: "It's no use + V-ing." },
		{ sentence: "I prefer walking to ____.", options: ["driving", "drive", "drove", "driven"], correct: 0, explanation: "Prefer V-ing to V-ing." },
		{ sentence: "This problem is too difficult for me ____ solve.", options: ["to", "for", "with", "that"], correct: 0, explanation: "Too ... for sb to V." },
		{ sentence: "It was ____ a boring film that I fell asleep.", options: ["such", "so", "very", "too"], correct: 0, explanation: "Such (a/an) + adj + N + that." },
		{ sentence: "The soup was ____ hot that I couldn't eat it.", options: ["so", "such", "too", "very"], correct: 0, explanation: "So + adj + that." },
		{ sentence: "Although it rained, ____ we went out.", options: ["", "but", "however", "so"], correct: 0, explanation: "Although không đi với but ở mệnh đề sau." },
		{ sentence: "Because it was raining, ____ we stayed home.", options: ["", "so", "but", "therefore"], correct: 0, explanation: "Because không dùng với so." },
		{ sentence: "Unless you ____ hard, you will fail.", options: ["work", "don't work", "worked", "working"], correct: 0, explanation: "Unless = If not. Không dùng phủ định sau unless." },
		{ sentence: "I ____ my hair cut yesterday.", options: ["had", "have", "has", "having"], correct: 0, explanation: "Cấu trúc nhờ vả: have sth done." },
		{ sentence: "He got his car ____ by a mechanic.", options: ["repaired", "repair", "repairing", "repairs"], correct: 0, explanation: "Get sth done." },
		{ sentence: "Neither Tom ____ Mary came.", options: ["nor", "or", "and", "but"], correct: 0, explanation: "Neither ... nor." },
		{ sentence: "Either you ____ I have to go.", options: ["or", "nor", "and", "but"], correct: 0, explanation: "Either ... or." },
		{ sentence: "Both John ____ his wife are doctors.", options: ["and", "or", "but", "with"], correct: 0, explanation: "Both ... and." },
		{ sentence: "Not only my mother ____ my father is happy.", options: ["but also", "but", "and", "or"], correct: 0, explanation: "Not only ... but also." },
		{ sentence: "Please turn ____ the light.", options: ["off", "out", "of", "away"], correct: 0, explanation: "Turn off (tắt)." },
		{ sentence: "Who looks ____ the baby?", options: ["after", "for", "at", "up"], correct: 0, explanation: "Look after (chăm sóc)." },
		{ sentence: "He gave ____ smoking.", options: ["up", "in", "on", "off"], correct: 0, explanation: "Give up (từ bỏ)." },
		{ sentence: "I ran ____ an old friend yesterday.", options: ["into", "out", "on", "up"], correct: 0, explanation: "Run into (tình cờ gặp)." },
		{ sentence: "We ran ____ of gas.", options: ["out", "in", "off", "up"], correct: 0, explanation: "Run out of (hết)." },
		{ sentence: "Put ____ your coat, it's cold.", options: ["on", "in", "off", "out"], correct: 0, explanation: "Put on (mặc vào)." },
		{ sentence: "Take ____ your shoes.", options: ["off", "out", "in", "up"], correct: 0, explanation: "Take off (cởi ra)." },
		{ sentence: "Can I try this shirt ____?", options: ["on", "in", "at", "up"], correct: 0, explanation: "Try on (thử đồ)." },
		{ sentence: "He is famous ____ his music.", options: ["for", "with", "about", "at"], correct: 0, explanation: "Famous for." },
		{ sentence: "I am fed up ____ his complaints.", options: ["with", "about", "of", "on"], correct: 0, explanation: "Fed up with (chán ngấy)." },
		{ sentence: "She is capable ____ doing it.", options: ["of", "for", "in", "at"], correct: 0, explanation: "Capable of." },
		{ sentence: "Are you aware ____ the danger?", options: ["of", "about", "with", "in"], correct: 0, explanation: "Aware of." },
		{ sentence: "This book belongs ____ me.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Belong to." },
		{ sentence: "He apologized ____ being late.", options: ["for", "to", "about", "with"], correct: 0, explanation: "Apologize for V-ing." },
		{ sentence: "I congratulated him ____ passing the exam.", options: ["on", "for", "in", "at"], correct: 0, explanation: "Congratulate on." },
	],
	B1: [
		{ sentence: "I ____ London since 1990.", options: ["have lived", "lived", "live", "am living"], correct: 0, explanation: "Hiện tại hoàn thành với 'since' + mốc thời gian." },
		{ sentence: "She ____ written three books.", options: ["has", "have", "did", "was"], correct: 0, explanation: "Hiện tại hoàn thành: S + has + V3." },
		{ sentence: "They ____ arrived by the time we got there.", options: ["had", "have", "has", "did"], correct: 0, explanation: "Quá khứ hoàn thành diễn tả hành động xảy ra trước hành động khác trong quá khứ." },
		{ sentence: "He said that he ____ the film before.", options: ["had seen", "saw", "has seen", "sees"], correct: 0, explanation: "Câu tường thuật lùi thì: QKĐ/HTHT -> QKHT." },
		{ sentence: "If I ____ you, I would study harder.", options: ["were", "was", "am", "be"], correct: 0, explanation: "Câu điều kiện loại 2 (giả định trái ngược hiện tại): 'were' dùng cho mọi ngôi." },
		{ sentence: "She asked me if I ____ swim.", options: ["could", "can", "will", "may"], correct: 0, explanation: "Tường thuật câu hỏi Yes/No: if + S + V(lùi thì)." },
		{ sentence: "The house ____ built in 1890.", options: ["was", "is", "has been", "had been"], correct: 0, explanation: "Bị động quá khứ đơn (có thời gian xác định)." },
		{ sentence: "I have ____ finished my work.", options: ["just", "yet", "ever", "fail"], correct: 0, explanation: "Trạng từ 'just' (vừa mới) dùng trong thì hoàn thành." },
		{ sentence: "Have you ____ eaten frogs?", options: ["ever", "never", "yet", "always"], correct: 0, explanation: "Dùng 'ever' trong câu hỏi trải nghiệm." },
		{ sentence: "We ____ to the cinema twice this month.", options: ["have been", "went", "go", "are going"], correct: 0, explanation: "Hành động lặp lại nhiều lần trong khoảng thời gian chưa kết thúc." },
		{ sentence: "After he ____ his homework, he went to bed.", options: ["had finished", "finished", "has finished", "finishes"], correct: 0, explanation: "Hành động xảy ra xong (QKHT) trước hành động khác (QKĐ)." },
		{ sentence: "She told me she ____ help me the next day.", options: ["would", "will", "can", "may"], correct: 0, explanation: "Tường thuật: will -> would, tomorrow -> the next day." },
		{ sentence: "When I arrived, the train ____.", options: ["had left", "left", "has left", "leaves"], correct: 0, explanation: "Tàu rời đi trước khi tôi đến (QKHT)." },
		{ sentence: "He asked me where I ____.", options: ["lived", "live", "did live", "lives"], correct: 0, explanation: "Tường thuật câu hỏi Wh-: từ để hỏi + S + V(lùi thì)." },
		{ sentence: "Unless you ____ now, you will be late.", options: ["leave", "don't leave", "left", "leaving"], correct: 0, explanation: "Unless = If not, đi với khẳng định." },
		{ sentence: "I wish I ____ a bigger house.", options: ["had", "have", "has", "having"], correct: 0, explanation: "Ước cho hiện tại: S + wish + S + V(quá khứ)." },
		{ sentence: "The letter ____ by John.", options: ["was written", "wrote", "writes", "writing"], correct: 0, explanation: "Bị động: be + V3." },
		{ sentence: "I haven't seen her ____ 3 years.", options: ["for", "since", "in", "from"], correct: 0, explanation: "'For' + khoảng thời gian." },
		{ sentence: "They ____ married for 10 years.", options: ["have been", "are", "were", "had been"], correct: 0, explanation: "Diễn tả trạng thái kéo dài từ quá khứ đến hiện tại." },
		{ sentence: "She said she ____ to the party.", options: ["couldn't go", "can't go", "won't go", "not go"], correct: 0, explanation: "Lùi thì: can't -> couldn't." },
		{ sentence: "He wanted to know if I ____ play guitar.", options: ["could", "can", "will", "may"], correct: 0, explanation: "Tường thuật câu hỏi nghi vấn." },
		{ sentence: "If I had money, I ____ buy a car.", options: ["would", "will", "can", "may"], correct: 0, explanation: "Điều kiện loại 2: S + would + V." },
		{ sentence: "The car ____ washed yet.", options: ["hasn't been", "hasn't", "didn't", "wasn't"], correct: 0, explanation: "Bị động thì HTHT phủ định: hasn't been V3." },
		{ sentence: "He ____ working here for 6 months.", options: ["has been", "is", "was", "had been"], correct: 0, explanation: "HTHT tiếp diễn nhấn mạnh tính liên tục." },
		{ sentence: "I saw the man ____ house was on fire.", options: ["whose", "who", "which", "whom"], correct: 0, explanation: "Đại từ quan hệ chỉ sở hữu." },
		{ sentence: "The reason ____ he left is unknown.", options: ["why", "which", "that", "where"], correct: 0, explanation: "Reason why." },
		{ sentence: "I look forward to ____ from you.", options: ["hearing", "hear", "heard", "hears"], correct: 0, explanation: "Look forward to + V-ing." },
		{ sentence: "It's no use ____ about it.", options: ["worrying", "worry", "to worry", "worried"], correct: 0, explanation: "It's no use + V-ing." },
		{ sentence: "I'm used to ____ up early.", options: ["getting", "get", "got", "to get"], correct: 0, explanation: "Be used to + V-ing (quen với)." },
		{ sentence: "He used to ____ smoke.", options: ["smoke", "smoking", "smoked", "to smoke"], correct: 0, explanation: "Used to + V (đã từng)." },
		{ sentence: "I would rather you ____ now.", options: ["went", "go", "gone", "going"], correct: 0, explanation: "Would rather + S + V(quá khứ) (muốn ai làm gì ngay)." },
		{ sentence: "It's time we ____ to bed.", options: ["went", "go", "gone", "going"], correct: 0, explanation: "It's time + S + V(quá khứ)." },
		{ sentence: "I'd better ____ now.", options: ["go", "to go", "going", "went"], correct: 0, explanation: "Had better + V (nên)." },
		{ sentence: "She suggested ____ to the beach.", options: ["going", "to go", "go", "went"], correct: 0, explanation: "Suggest + V-ing." },
		{ sentence: "He admitted ____ the money.", options: ["stealing", "to steal", "steal", "stolen"], correct: 0, explanation: "Admit + V-ing." },
		{ sentence: "I regret ____ you that...", options: ["to tell", "telling", "tell", "told"], correct: 0, explanation: "Regret to V: lấy làm tiếc khi phải làm gì (thông báo)." },
		{ sentence: "I regret ____ the car.", options: ["buying", "to buy", "buy", "bought"], correct: 0, explanation: "Regret + V-ing: hối hận vì đã làm gì." },
		{ sentence: "Do you mind if I ____ the window?", options: ["open", "opening", "opened", "to open"], correct: 0, explanation: "Do you mind if I + V(hiện tại)." },
		{ sentence: "Would you mind if I ____ the window?", options: ["opened", "open", "opening", "to open"], correct: 0, explanation: "Would you mind if I + V(quá khứ)." },
		{ sentence: "Despite ____ tired, he worked hard.", options: ["being", "be", "is", "was"], correct: 0, explanation: "Despite + V-ing/N." },
		{ sentence: "In spite of the rain, we ____ out.", options: ["went", "go", "gone", "going"], correct: 0, explanation: "Mệnh đề chính chia quá khứ đơn theo ngữ cảnh." },
		{ sentence: "This is the first time I ____ sushi.", options: ["have eaten", "eat", "ate", "eating"], correct: 0, explanation: "The first time + HTHT." },
		{ sentence: "By the time you return, I ____.", options: ["will have finished", "finished", "finish", "have finished"], correct: 0, explanation: "Tương lai hoàn thành: will have V3." },
		{ sentence: "He promised ____ lie again.", options: ["not to", "to not", "shouldn't", "won't"], correct: 0, explanation: "Promise not to V." },
		{ sentence: "She accused him ____ stealing.", options: ["of", "for", "with", "on"], correct: 0, explanation: "Accuse sb of V-ing." },
		{ sentence: "He insists ____ paying.", options: ["on", "in", "at", "for"], correct: 0, explanation: "Insist on." },
		{ sentence: "I warned him ____ touch it.", options: ["not to", "don't", "doesn't", "didn't"], correct: 0, explanation: "Warn sb not to V." },
		{ sentence: "Remind me ____ call her.", options: ["to", "for", "of", "about"], correct: 0, explanation: "Remind sb to V." },
		{ sentence: "It was ____ nice day that we went out.", options: ["such a", "so", "such", "very"], correct: 0, explanation: "Such a + adj + N." },
		{ sentence: "The coffee was ____ hot for me to drink.", options: ["too", "so", "very", "enough"], correct: 0, explanation: "Too + adj + for sb to V." },
		{ sentence: "This box is ____ heavy to lift.", options: ["too", "enough", "so", "such"], correct: 0, explanation: "Too ... to." },
		{ sentence: "The room isn't big ____ for us.", options: ["enough", "too", "so", "very"], correct: 0, explanation: "Adj + enough." },
		{ sentence: "If I ____ known, I would have told you.", options: ["had", "have", "has", "did"], correct: 0, explanation: "Điều kiện loại 3: If + QKHT." },
		{ sentence: "I wish I ____ gone to the party.", options: ["had", "have", "would", "was"], correct: 0, explanation: "Ước quá khứ: Wish + QKHT." },
		{ sentence: "The bridge ____ repair.", options: ["needs", "need", "needing", "needed"], correct: 0, explanation: "Vật + need + V-ing/Noun (nghĩa bị động) hoặc needs + repair(noun)." },
		{ sentence: "My watch needs ____.", options: ["repairing", "to repair", "repaired", "repair"], correct: 0, explanation: "Need + V-ing (bị động)." },
		{ sentence: "I had my car ____.", options: ["washed", "wash", "washing", "to wash"], correct: 0, explanation: "Had sth done." },
		{ sentence: "He ____ to have lost his way.", options: ["appears", "appearing", "appear", "appeared"], correct: 0, explanation: "Appear to V." },
		{ sentence: "She seems ____ be happy.", options: ["to", "for", "at", "on"], correct: 0, explanation: "Seem to V." },
		{ sentence: "It is likely ____ rain.", options: ["to", "that", "it", "so"], correct: 0, explanation: "Be likely to V." },
		{ sentence: "He is believed ____ be rich.", options: ["to", "that", "it", "so"], correct: 0, explanation: "Be believed to V." },
		{ sentence: "People say that he ____ rich.", options: ["is", "to be", "being", "been"], correct: 0, explanation: "People say that + Clause." },
		{ sentence: "He is said ____ eaten the cake.", options: ["to have", "to has", "having", "have"], correct: 0, explanation: "To have V3 (xảy ra trước)." },
		{ sentence: "Don't forget ____ the door.", options: ["to lock", "locking", "lock", "locked"], correct: 0, explanation: "Forget to V (nhiệm vụ)." },
		{ sentence: "I'll never forget ____ her.", options: ["meeting", "to meet", "meet", "met"], correct: 0, explanation: "Forget V-ing (kỷ niệm)." },
		{ sentence: "Please stop ____ noise.", options: ["making", "to make", "make", "made"], correct: 0, explanation: "Stop making noise (ngừng làm ồn)." },
		{ sentence: "Try ____ this door.", options: ["opening", "to open", "open", "opened"], correct: 0, explanation: "Try V-ing (thử)." },
		{ sentence: "Try ____ hard.", options: ["to study", "studying", "study", "studied"], correct: 0, explanation: "Try to V (cố gắng)." },
		{ sentence: "I remember ____ him somewhere.", options: ["meeting", "to meet", "meet", "met"], correct: 0, explanation: "Remember V-ing (nhớ đã làm)." },
		{ sentence: "Remember ____ the bill.", options: ["to pay", "paying", "pay", "paid"], correct: 0, explanation: "Remember to V (nhớ phải làm)." },
		{ sentence: "She made him ____ the floor.", options: ["clean", "to clean", "cleaning", "cleaned"], correct: 0, explanation: "Make sb V." },
		{ sentence: "He was made ____ the floor.", options: ["to clean", "clean", "cleaning", "cleaned"], correct: 0, explanation: "Be made to V." },
		{ sentence: "Let him ____ out.", options: ["go", "to go", "going", "went"], correct: 0, explanation: "Let sb V." },
		{ sentence: "The building ____ destroyed by the storm.", options: ["was", "is", "has", "had"], correct: 0, explanation: "Bị động quá khứ." },
		{ sentence: "Newspapers ____ delivered every day.", options: ["are", "is", "were", "was"], correct: 0, explanation: "Bị động hiện tại đơn." },
		{ sentence: "Who ____ the telephone?", options: ["invented", "invent", "invents", "invention"], correct: 0, explanation: "Câu hỏi chủ ngữ Wh-." },
		{ sentence: "The window ____ broken by the boy.", options: ["was", "is", "were", "are"], correct: 0, explanation: "Bị động QKĐ." },
		{ sentence: "I have my hair ____ every month.", options: ["cut", "cutting", "to cut", "cuts"], correct: 0, explanation: "Have sth done." },
		{ sentence: "We got the roof ____.", options: ["mended", "mend", "mending", "to mend"], correct: 0, explanation: "Get sth done." },
		{ sentence: "I heard him ____ out.", options: ["go", "to go", "went", "gone"], correct: 0, explanation: "Hear sb V (trọn vẹn hành động)." },
		{ sentence: "I heard him ____ down the stairs.", options: ["coming", "come", "came", "to come"], correct: 0, explanation: "Hear sb V-ing (một phần)." },
		{ sentence: "I saw her ____ the street.", options: ["cross", "crossed", "to cross", "crosses"], correct: 0, explanation: "See sb V." },
		{ sentence: "I can smell something ____.", options: ["burning", "burn", "to burn", "burnt"], correct: 0, explanation: "Smell sth V-ing." },
		{ sentence: "She caught him ____ her bag.", options: ["stealing", "steal", "to steal", "stolen"], correct: 0, explanation: "Catch sb V-ing." },
		{ sentence: "I found him ____ in the garden.", options: ["sleeping", "sleep", "to sleep", "slept"], correct: 0, explanation: "Find sb V-ing." },
		{ sentence: "Don't keep me ____.", options: ["waiting", "wait", "to wait", "waited"], correct: 0, explanation: "Keep sb V-ing." },
		{ sentence: "Do you fancy ____ out tonight?", options: ["going", "to go", "go", "went"], correct: 0, explanation: "Fancy + V-ing." },
		{ sentence: "I can't help ____ at him.", options: ["laughing", "to laugh", "laugh", "laughed"], correct: 0, explanation: "Can't help + V-ing (không nhịn được)." },
		{ sentence: "Do you mind ____?", options: ["smoking", "to smoke", "smoke", "smoked"], correct: 0, explanation: "Mind + V-ing." },
		{ sentence: "Would you like ____ a drink?", options: ["to have", "having", "have", "had"], correct: 0, explanation: "Would like to V." },
		{ sentence: "She is qualified ____ the job.", options: ["for", "to", "at", "in"], correct: 0, explanation: "Qualified for." },
		{ sentence: "He is famous ____ his paintings.", options: ["for", "with", "about", "in"], correct: 0, explanation: "Famous for." },
		{ sentence: "I am doubtful ____ his ability.", options: ["of", "about", "for", "with"], correct: 0, explanation: "Doubtful of." },
		{ sentence: "She is jealous ____ her sister.", options: ["of", "about", "for", "with"], correct: 0, explanation: "Jealous of." },
		{ sentence: "I am familiar ____ this topic.", options: ["with", "about", "for", "of"], correct: 0, explanation: "Familiar with." },
		{ sentence: "He is responsible ____ the error.", options: ["for", "to", "with", "of"], correct: 0, explanation: "Responsible for." },
	],
	B2: [
		{ sentence: "If I ____ you, I ____ accept the offer.", options: ["were / would", "was / will", "am / will", "be / would"], correct: 0, explanation: "Điều kiện loại 2: If + S + were, S + would + V." },
		{ sentence: "The book ____ by the time I arrived.", options: ["had been sold", "was sold", "sold", "has been sold"], correct: 0, explanation: "Bị động quá khứ hoàn thành: had been V3." },
		{ sentence: "I wish I ____ harder for the exam apart from English.", options: ["had studied", "studied", "study", "have studied"], correct: 0, explanation: "Ước cho quá khứ: Wish + QKHT." },
		{ sentence: "If it ____ yesterday, we would have gone out.", options: ["hadn't rained", "didn't rain", "weren't raining", "hasn't rained"], correct: 0, explanation: "Điều kiện loại 3: If + QKHT, S + would have V3." },
		{ sentence: "She said she ____ working there since 2010.", options: ["had been", "has been", "was", "is"], correct: 0, explanation: "Tường thuật: HTHTTD -> QKHTTD." },
		{ sentence: "By next year, we ____ here for 20 years.", options: ["will have lived", "have lived", "will live", "live"], correct: 0, explanation: "Tương lai hoàn thành: will have V3 + for + time." },
		{ sentence: "This painting is believed ____ by Picasso.", options: ["to have been painted", "to be painted", "painting", "painted"], correct: 0, explanation: "Bị động bị động cách: believed to have been V3." },
		{ sentence: "No sooner ____ I arrived than the train left.", options: ["had", "did", "have", "was"], correct: 0, explanation: "Cấu trúc đảo ngữ: No sooner + had + S + V3 + than..." },
		{ sentence: "Hardly ____ sat down when the phone rang.", options: ["had I", "did I", "have I", "was I"], correct: 0, explanation: "Hardly + had + S + V3 + when..." },
		{ sentence: "Only when I call ____ you come.", options: ["will", "do", "did", "are"], correct: 0, explanation: "Đảo ngữ với Only when + clause + auxiliary + S + V." },
		{ sentence: "Not until yesterday ____ the truth.", options: ["did I know", "I knew", "I know", "had I known"], correct: 0, explanation: "Not until + time/clause + did + S + V." },
		{ sentence: "Never ____ such a beautiful sight.", options: ["have I seen", "I have seen", "did I see", "seen I"], correct: 0, explanation: "Đảo ngữ với Never: Never + aux + S + V." },
		{ sentence: "Little ____ he know about the surprise.", options: ["did", "does", "do", "had"], correct: 0, explanation: "Đảo ngữ với Little: Little + did + S + V." },
		{ sentence: "Had I known, I ____ helped you.", options: ["would have", "will have", "would", "had"], correct: 0, explanation: "Đảo ngữ điều kiện loại 3: Had + S + V3, S + would have V3." },
		{ sentence: "Should you see him, ____ him to call me.", options: ["tell", "told", "telling", "to tell"], correct: 0, explanation: "Đảo ngữ điều kiện loại 1: Should + S + V, mệnh lệnh." },
		{ sentence: "Were I you, I ____ go there.", options: ["wouldn't", "won't", "don't", "didn't"], correct: 0, explanation: "Đảo ngữ điều kiện loại 2: Were + S + ..., S + would + V." },
		{ sentence: "It is essential that he ____ here on time.", options: ["be", "is", "was", "were"], correct: 0, explanation: "Thức giả định (Subjunctive): It is essential that S + (should) V nguyên thể." },
		{ sentence: "I suggest that she ____ harder.", options: ["study", "studies", "studied", "studying"], correct: 0, explanation: "Subjunctive sau suggest: S + (should) V nguyên thể." },
		{ sentence: "The teacher demanded that everyone ____ quiet.", options: ["keep", "keeps", "kept", "keeping"], correct: 0, explanation: "Subjunctive sau demand." },
		{ sentence: "God ____ the Queen!", options: ["save", "saves", "saved", "saving"], correct: 0, explanation: "Câu cầu khiến (Subjunctive): God save..." },
		{ sentence: "Whatever ____, I will always love you.", options: ["happens", "happen", "happened", "happening"], correct: 0, explanation: "Whatever happens (HTĐ)." },
		{ sentence: "However rich he ____, he isn't happy.", options: ["is", "be", "was", "been"], correct: 0, explanation: "However + adj + S + V." },
		{ sentence: "No matter how ____ you try, you can't lift it.", options: ["hard", "hardly", "hardness", "harder"], correct: 0, explanation: "No matter how + adj/adv." },
		{ sentence: "Unless you ____ been there, you wouldn't understand.", options: ["had", "have", "has", "did"], correct: 0, explanation: "Unless trong ngữ cảnh quá khứ (loại 3)." },
		{ sentence: "Supposing you ____ the lottery, what would you do?", options: ["won", "win", "winning", "wins"], correct: 0, explanation: "Supposing = If (loại 2)." },
		{ sentence: "Provided that you ____ the money back, I will lend it.", options: ["pay", "paying", "paid", "pays"], correct: 0, explanation: "Provided that = If (loại 1)." },
		{ sentence: "In case it ____, bring an umbrella.", options: ["rains", "rain", "rained", "raining"], correct: 0, explanation: "In case + HTĐ." },
		{ sentence: "It's high time you ____ a job.", options: ["got", "get", "getting", "have got"], correct: 0, explanation: "It's high time + S + V(quá khứ)." },
		{ sentence: "I'd rather you ____ smoke here.", options: ["didn't", "don't", "not", "won't"], correct: 0, explanation: "Would rather + S + V(quá khứ) (phủ định)." },
		{ sentence: "The meeting ____ off due to bad weather.", options: ["was called", "called", "has called", "is calling"], correct: 0, explanation: "Bị động phrase verb: call off -> was called off." },
		{ sentence: "He is thought ____ the richest man.", options: ["to be", "being", "is", "was"], correct: 0, explanation: "Bị động: thought to be." },
		{ sentence: "It is rumored that he ____ left the country.", options: ["has", "have", "had", "having"], correct: 0, explanation: "It is rumored that S + V." },
		{ sentence: "Having ____ his work, he went home.", options: ["finished", "finishing", "finish", "finishes"], correct: 0, explanation: "Perfect Participle: Having V3 (nhấn mạnh hoàn tất trước)." },
		{ sentence: "____ by a snake, he went to the hospital.", options: ["Bitten", "Biting", "Bit", "Byte"], correct: 0, explanation: "Past Participle rút gọn câu bị động." },
		{ sentence: "____ his car, he walked to work.", options: ["Having sold", "Selling", "Sold", "Sell"], correct: 0, explanation: "Rút gọn chủ ngữ (đã bán xe xong rồi đi bộ)." },
		{ sentence: "Seen from the distance, the mountain ____ like a giant.", options: ["looks", "look", "looking", "looked"], correct: 0, explanation: "Rút gọn bị động: Seen from..." },
		{ sentence: "Not ____ what to do, he called his mom.", options: ["knowing", "known", "knew", "know"], correct: 0, explanation: "Rút gọn chủ động phủ định: Not knowing." },
		{ sentence: "To ____ the truth, I don't like it.", options: ["tell", "say", "speak", "talk"], correct: 0, explanation: "To tell the truth (thành ngữ)." },
		{ sentence: "Generally ____, men are stronger than women.", options: ["speaking", "speak", "spoken", "spoke"], correct: 0, explanation: "Generally speaking." },
		{ sentence: "Judging ____ appearance, he is wealthy.", options: ["from", "by", "to", "at"], correct: 0, explanation: "Judging from/by." },
		{ sentence: "Considering ____ young he is, he is smart.", options: ["how", "what", "that", "which"], correct: 0, explanation: "Considering how..." },
		{ sentence: "There's no point ____ arguing.", options: ["in", "on", "at", "for"], correct: 0, explanation: "There's no point in V-ing." },
		{ sentence: "It's worth ____ the museum.", options: ["visiting", "to visit", "visit", "visited"], correct: 0, explanation: "It's worth V-ing." },
		{ sentence: "I have difficulty ____ English.", options: ["speaking", "to speak", "speak", "spoke"], correct: 0, explanation: "Have difficulty (in) V-ing." },
		{ sentence: "He spent 2 hours ____ his homework.", options: ["doing", "to do", "do", "done"], correct: 0, explanation: "Spend time V-ing." },
		{ sentence: "It took me 30 minutes ____ to school.", options: ["to go", "going", "go", "went"], correct: 0, explanation: "It takes sb time to V." },
		{ sentence: "Make yourself ____ home.", options: ["at", "in", "on", "to"], correct: 0, explanation: "Make yourself at home." },
		{ sentence: "Help yourself ____ some cake.", options: ["to", "with", "for", "on"], correct: 0, explanation: "Help yourself to." },
		{ sentence: "She is devoted ____ her family.", options: ["to", "for", "with", "on"], correct: 0, explanation: "Devoted to." },
		{ sentence: "He is addicted ____ gaming.", options: ["to", "with", "on", "in"], correct: 0, explanation: "Addicted to." },
		{ sentence: "I am opposed ____ the plan.", options: ["to", "with", "for", "on"], correct: 0, explanation: "Opposed to." },
		{ sentence: "She is accustomed ____ living alone.", options: ["to", "with", "for", "in"], correct: 0, explanation: "Accustomed to V-ing." },
		{ sentence: "He was prevented ____ entering.", options: ["from", "to", "with", "of"], correct: 0, explanation: "Prevent from." },
		{ sentence: "I discouraged him ____ quitting.", options: ["from", "to", "with", "of"], correct: 0, explanation: "Discourage from." },
		{ sentence: "He is keen ____ succeed.", options: ["to", "on", "of", "in"], correct: 0, explanation: "Keen to V (muốn làm). Keen on V-ing (thích)." },
		{ sentence: "I am confident ____ winning.", options: ["of", "in", "for", "about"], correct: 0, explanation: "Confident of." },
		{ sentence: "He is eligible ____ the position.", options: ["for", "to", "in", "at"], correct: 0, explanation: "Eligible for." },
		{ sentence: "The city is famous ____ its food.", options: ["for", "to", "with", "about"], correct: 0, explanation: "Famous for." },
		{ sentence: "He is angry ____ me.", options: ["with", "to", "about", "for"], correct: 0, explanation: "Angry with sb." },
		{ sentence: "He is angry ____ what I said.", options: ["about", "with", "for", "to"], correct: 0, explanation: "Angry about sth." },
		{ sentence: "I am disappointed ____ the result.", options: ["with", "to", "for", "on"], correct: 0, explanation: "Disappointed with/at/about." },
		{ sentence: "She is envious ____ my success.", options: ["of", "about", "for", "with"], correct: 0, explanation: "Envious of." },
		{ sentence: "He is guilty ____ the crime.", options: ["of", "for", "with", "about"], correct: 0, explanation: "Guilty of." },
		{ sentence: "He is innocent ____ the crime.", options: ["of", "from", "fo", "with"], correct: 0, explanation: "Innocent of." },
		{ sentence: "I am proud ____ you.", options: ["of", "about", "with", "for"], correct: 0, explanation: "Proud of." },
		{ sentence: "She is scared ____ ghosts.", options: ["of", "about", "with", "for"], correct: 0, explanation: "Scared of." },
		{ sentence: "He is short ____ money.", options: ["of", "in", "on", "with"], correct: 0, explanation: "Short of." },
		{ sentence: "I am suspicious ____ him.", options: ["of", "about", "with", "for"], correct: 0, explanation: "Suspicious of." },
		{ sentence: "She is tired ____ working.", options: ["of", "with", "about", "from"], correct: 0, explanation: "Tired of (chán)." },
		{ sentence: "He is tired ____ running.", options: ["from", "of", "with", "about"], correct: 0, explanation: "Tired from (mệt do)." },
		{ sentence: "This car is superior ____ that one.", options: ["to", "than", "from", "with"], correct: 0, explanation: "Superior to." },
		{ sentence: "This is inferior ____ that.", options: ["to", "than", "from", "with"], correct: 0, explanation: "Inferior to." },
		{ sentence: "He is junior ____ me.", options: ["to", "than", "from", "with"], correct: 0, explanation: "Junior to." },
		{ sentence: "She is senior ____ me.", options: ["to", "than", "from", "with"], correct: 0, explanation: "Senior to." },
		{ sentence: "The problem relates ____ money.", options: ["to", "with", "for", "of"], correct: 0, explanation: "Relate to." },
		{ sentence: "Concentrate ____ your work.", options: ["on", "in", "at", "to"], correct: 0, explanation: "Concentrate on." },
		{ sentence: "Depend ____ me.", options: ["on", "in", "at", "to"], correct: 0, explanation: "Depend on." },
		{ sentence: "Rely ____ yourself.", options: ["on", "in", "at", "to"], correct: 0, explanation: "Rely on." },
		{ sentence: "Count ____ me.", options: ["on", "in", "at", "to"], correct: 0, explanation: "Count on." },
		{ sentence: "Look ____ the word in the dictionary.", options: ["up", "for", "at", "after"], correct: 0, explanation: "Look up (tra cứu)." },
		{ sentence: "He takes ____ his father.", options: ["after", "on", "off", "up"], correct: 0, explanation: "Take after (giống)." },
		{ sentence: "The plane took ____ at 6 PM.", options: ["off", "on", "up", "out"], correct: 0, explanation: "Take off (cất cánh)." },
		{ sentence: "I can't put ____ with his behavior.", options: ["up", "on", "off", "in"], correct: 0, explanation: "Put up with (chịu đựng)." },
		{ sentence: "Let's put ____ the meeting.", options: ["off", "on", "up", "out"], correct: 0, explanation: "Put off (hoãn)." },
		{ sentence: "Who brought ____ this topic?", options: ["up", "on", "in", "out"], correct: 0, explanation: "Bring up (đề cập)." },
		{ sentence: "She brought ____ 3 children.", options: ["up", "on", "in", "out"], correct: 0, explanation: "Bring up (nuôi nấng)." },
		{ sentence: "Call me ____ when you arrive.", options: ["back", "on", "up", "for"], correct: 0, explanation: "Call back." },
		{ sentence: "I will pick you ____ at 7.", options: ["up", "on", "in", "off"], correct: 0, explanation: "Pick up (đón)." },
		{ sentence: "He turned ____ the job.", options: ["down", "up", "off", "on"], correct: 0, explanation: "Turn down (từ chối)." },
		{ sentence: "Please turn ____ the volume.", options: ["up", "on", "in", "out"], correct: 0, explanation: "Turn up (vặn to) / Turn down (vặn nhỏ)." },
		{ sentence: "He showed ____ late.", options: ["up", "on", "off", "in"], correct: 0, explanation: "Show up (xuất hiện)." },
		{ sentence: "The bomb went ____.", options: ["off", "on", "up", "out"], correct: 0, explanation: "Go off (nổ)." },
		{ sentence: "The lights went ____.", options: ["out", "off", "on", "up"], correct: 0, explanation: "Go out (tắt)." },
		{ sentence: "Go ____ working.", options: ["on", "off", "up", "out"], correct: 0, explanation: "Go on (tiếp tục)." },
		{ sentence: "Carry ____ with your work.", options: ["on", "out", "up", "off"], correct: 0, explanation: "Carry on (tiếp tục)." },
		{ sentence: "We need to carry ____ a survey.", options: ["out", "on", "up", "off"], correct: 0, explanation: "Carry out (thực hiện)." },
		{ sentence: "He broke ____ with his girlfriend.", options: ["up", "off", "down", "out"], correct: 0, explanation: "Break up (chia tay)." },
		{ sentence: "The car broke ____.", options: ["down", "up", "off", "out"], correct: 0, explanation: "Break down (hỏng)." },
		{ sentence: "Burglars broke ____ the house.", options: ["into", "up", "off", "down"], correct: 0, explanation: "Break into (đột nhập)." },
		{ sentence: "War broke ____ in 1939.", options: ["out", "up", "off", "down"], correct: 0, explanation: "Break out (nổ ra)." },
	],
	C1: [
		{ sentence: "Seldom ____ such a chaotic scene.", options: ["have I seen", "I saw", "did I see", "seen I"], correct: 0, explanation: "Đảo ngữ với Seldom." },
		{ sentence: "Under no circumstances ____ you open this door.", options: ["should", "do", "are", "have"], correct: 0, explanation: "Đảo ngữ với Under no circumstances." },
		{ sentence: "Little ____ that he was being watched.", options: ["did he realize", "he realized", "he did realize", "realized he"], correct: 0, explanation: "Đảo ngữ với Little." },
		{ sentence: "Not only ____ late, but he also forgot his book.", options: ["did he arrive", "he arrived", "arrived he", "he did arrive"], correct: 0, explanation: "Đảo ngữ với Not only." },
		{ sentence: "Only after I asked him ____ the truth.", options: ["did he tell", "told he", "he told", "he did tell"], correct: 0, explanation: "Đảo ngữ với Only after." },
		{ sentence: "Were it not for your help, I ____.", options: ["would have failed", "failed", "will fail", "had failed"], correct: 0, explanation: "Câu điều kiện loại 3 đảo ngữ (Were it not for = If it hadn't been for)." },
		{ sentence: "But for his advice, I ____ lost.", options: ["would be", "will be", "am", "was"], correct: 0, explanation: "But for + Noun phrase (~ If clause)." },
		{ sentence: "Had I known you were coming, I ____ a cake.", options: ["would have baked", "baked", "will bake", "bake"], correct: 0, explanation: "Đảo ngữ loại 3." },
		{ sentence: "Should you need assistance, please ____ us.", options: ["contact", "contacted", "contacting", "to contact"], correct: 0, explanation: "Đảo ngữ loại 1: Should + S + V." },
		{ sentence: "Unless ____, I won't go.", options: ["invited", "inviting", "invite", "invites"], correct: 0, explanation: "Rút gọn mệnh đề: Unless (I am) invited." },
		{ sentence: "Hardly had I arrived ____ the trouble started.", options: ["when", "than", "then", "after"], correct: 0, explanation: "Hardly ... when." },
		{ sentence: "No sooner had we left ____ it began to rain.", options: ["than", "when", "then", "after"], correct: 0, explanation: "No sooner ... than." },
		{ sentence: "Scarcely had he spoken ____ she interrupted.", options: ["when", "than", "then", "after"], correct: 0, explanation: "Scarcely ... when." },
		{ sentence: "It was not until midnight ____ he returned.", options: ["that", "when", "then", "after"], correct: 0, explanation: "Cấu trúc nhấn mạnh: It was not until ... that." },
		{ sentence: "Rarely ____ eaten such delicious food.", options: ["have I", "I have", "did I", "I did"], correct: 0, explanation: "Đảo ngữ với Rarely." },
		{ sentence: "Nowhere ____ find such kindness.", options: ["will you", "you will", "did you", "you did"], correct: 0, explanation: "Đảo ngữ với Nowhere." },
		{ sentence: "On no account ____ be disturbed.", options: ["must the manager", "the manager must", "mustn't the manager", "the manager mustn't"], correct: 0, explanation: "Đảo ngữ với On no account." },
		{ sentence: "In no way ____ responsible for this.", options: ["am I", "I am", "do I", "I do"], correct: 0, explanation: "Đảo ngữ với In no way." },
		{ sentence: "By no means ____ true.", options: ["is this", "this is", "does this", "this does"], correct: 0, explanation: "Đảo ngữ với By no means." },
		{ sentence: "So angry ____ that he slammed the door.", options: ["was he", "he was", "did he", "he did"], correct: 0, explanation: "Đảo ngữ với So + adj." },
		{ sentence: "Such ____ that we couldn't go out.", options: ["was the storm", "the storm was", "did the storm", "the storm did"], correct: 0, explanation: "Đảo ngữ với Such + be + N." },
		{ sentence: "Strange ____ it may seem, I like it.", options: ["as", "so", "though", "although"], correct: 0, explanation: "Adj + as + S + V." },
		{ sentence: "Try ____ he might, he couldn't lift it.", options: ["as", "so", "though", "although"], correct: 0, explanation: "Try as sbd might." },
		{ sentence: "Much ____ I respect him, I disagree.", options: ["as", "so", "though", "since"], correct: 0, explanation: "Much as (Mặc dù)." },
		{ sentence: "Never before ____ such a crisis.", options: ["have we faced", "we have faced", "did we face", "we face"], correct: 0, explanation: "Đảo ngữ Never before." },
		{ sentence: "____ what happens, stay calm.", options: ["No matter", "Whatever", "However", "Even if"], correct: 0, explanation: "No matter what." },
		{ sentence: "Be that ____ it may, I still refuse.", options: ["as", "so", "if", "when"], correct: 0, explanation: "Be that as it may (Dù vậy)." },
		{ sentence: "Come what ____, I will support you.", options: ["may", "might", "will", "can"], correct: 0, explanation: "Come what may (Dù chuyện gì xảy ra)." },
		{ sentence: "Suffice it to ____, we won.", options: ["say", "tell", "speak", "talk"], correct: 0, explanation: "Suffice it to say (Chỉ cần nói là)." },
		{ sentence: "____ told me, I would have come.", options: ["Had you", "If you", "Did you", "You had"], correct: 0, explanation: "Đảo ngữ loại 3." },
		{ sentence: "Assuming that X ____ true, Y is false.", options: ["is", "be", "was", "were"], correct: 0, explanation: "Assuming that." },
		{ sentence: "Whatever you do, don't ____ up.", options: ["give", "giving", "gave", "given"], correct: 0, explanation: "Mệnh lệnh." },
		{ sentence: "It is high time the government ____ action.", options: ["took", "take", "taking", "taken"], correct: 0, explanation: "It is high time + S + V(past)." },
		{ sentence: "If I ____ to win, I would be happy.", options: ["were", "was", "am", "be"], correct: 0, explanation: "If + S + to V (tương lai trong quá khứ/giả định)." },
		{ sentence: "Suppose you ____ job, what would you do?", options: ["lost", "lose", "losing", "losed"], correct: 0, explanation: "Suppose = If." },
		{ sentence: "Even if it ____ rains, we will play.", options: ["", "is", "will", "does"], correct: 0, explanation: "Even if + present." },
		{ sentence: "Whether he comes ____ not, we start.", options: ["or", "and", "but", "so"], correct: 0, explanation: "Whether ... or not." },
		{ sentence: "Rich ____ he is, he is mean.", options: ["as", "though", "although", "but"], correct: 0, explanation: "Adj + as + S + V." },
		{ sentence: "Loudly ____ he shouted, no one heard.", options: ["though", "as", "although", "even"], correct: 0, explanation: "Adv + though + S + V." },
		{ sentence: "Naked ____ the eye, bacteria are invisible.", options: ["to", "for", "with", "at"], correct: 0, explanation: "Naked to the eye (mắt thường)." },
		{ sentence: "Dependent ____ charity, he survived.", options: ["on", "in", "at", "for"], correct: 0, explanation: "Dependent on." },
		{ sentence: "Irrespective ____ age, anyone can join.", options: ["of", "for", "to", "with"], correct: 0, explanation: "Irrespective of (bất kể)." },
		{ sentence: "Regardless ____ the cost, I want it.", options: ["of", "for", "to", "with"], correct: 0, explanation: "Regardless of." },
		{ sentence: "Prior ____ the meeting, we ate.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Prior to." },
		{ sentence: "According ____ the report, sales differ.", options: ["to", "for", "with", "of"], correct: 0, explanation: "According to." },
		{ sentence: "Thanks ____ your help, we succeeded.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Thanks to." },
		{ sentence: "Due ____ the rain, we stopped.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Due to." },
		{ sentence: "Owing ____ his effort, he passed.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Owing to." },
		{ sentence: "On behalf ____ the company, I welcome you.", options: ["of", "for", "with", "to"], correct: 0, explanation: "On behalf of." },
		{ sentence: "In terms ____ quality, it is the best.", options: ["of", "for", "with", "to"], correct: 0, explanation: "In terms of." },
		{ sentence: "With a view ____ expanding, we hired more.", options: ["to", "for", "with", "of"], correct: 0, explanation: "With a view to + V-ing/N." },
		{ sentence: "In addition ____ English, he speaks French.", options: ["to", "for", "with", "of"], correct: 0, explanation: "In addition to." },
		{ sentence: "Contrary ____ popular belief, pigs are smart.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Contrary to." },
		{ sentence: "Apart ____ me, everyone went.", options: ["from", "to", "with", "of"], correct: 0, explanation: "Apart from." },
		{ sentence: "As well ____ French, she speaks German.", options: ["as", "to", "with", "of"], correct: 0, explanation: "As well as." },
		{ sentence: "Instead ____ going out, we stayed home.", options: ["of", "for", "to", "with"], correct: 0, explanation: "Instead of." },
		{ sentence: "In spite ____ his age, he runs fast.", options: ["of", "for", "to", "with"], correct: 0, explanation: "In spite of." },
		{ sentence: "For fear ____ being late, he ran.", options: ["of", "for", "to", "with"], correct: 0, explanation: "For fear of." },
		{ sentence: "By virtue ____ his power, he decided.", options: ["of", "for", "to", "with"], correct: 0, explanation: "By virtue of." },
		{ sentence: "In the event ____ fire, use stairs.", options: ["of", "for", "to", "with"], correct: 0, explanation: "In the event of." },
		{ sentence: "Not only ____ study, but he also works.", options: ["does he", "he does", "did he", "he did"], correct: 0, explanation: "Đảo ngữ Not only." },
		{ sentence: "Neither ____ I nor my brother likes it.", options: ["do", "does", "did", "have"], correct: 0, explanation: "Neither ... nor (động từ theo chủ ngữ gần nhất 'my brother' - wait, 'brother' is singular, so 'likes' is fine. But inversion after Neither? No, 'Neither I nor my brother' is subject. 'Neither do I' is inversion. This structure is Subject)." },
		{ sentence: "Not until the film ended ____ leave.", options: ["did we", "we did", "we left", "left we"], correct: 0, explanation: "Not until." },
		{ sentence: "Only by working hard ____ succeed.", options: ["will you", "you will", "did you", "you did"], correct: 0, explanation: "Only by + V-ing + aux + S." },
		{ sentence: "Only later ____ realize my mistake.", options: ["did I", "I did", "I realized", "realized I"], correct: 0, explanation: "Only later + did + S." },
		{ sentence: "At no time ____ she aware of it.", options: ["was", "is", "did", "does"], correct: 0, explanation: "At no time + aux." },
		{ sentence: "On no condition ____ you touch this.", options: ["should", "do", "are", "have"], correct: 0, explanation: "On no condition." },
		{ sentence: "I prefer reading to ____.", options: ["watching", "watch", "to watch", "watched"], correct: 0, explanation: "Prefer V-ing to V-ing." },
		{ sentence: "It is no use ____ him.", options: ["asking", "ask", "to ask", "asked"], correct: 0, explanation: "It is no use V-ing." },
		{ sentence: "There is no point ____ worrying.", options: ["in", "on", "at", "of"], correct: 0, explanation: "There is no point in." },
		{ sentence: "It won't be long ____ he arrives.", options: ["before", "after", "when", "until"], correct: 0, explanation: "It won't be long before." },
		{ sentence: "Hardly a day goes by ____ I don't think of her.", options: ["without", "when", "that", "but"], correct: 2, explanation: "Goes by that (mà)." },
		{ sentence: "I have no intention ____ resigning.", options: ["of", "to", "for", "in"], correct: 0, explanation: "Intention of." },
		{ sentence: "He has no chance ____ winning.", options: ["of", "to", "for", "in"], correct: 0, explanation: "Chance of." },
		{ sentence: "There is no hope ____ success.", options: ["of", "to", "for", "in"], correct: 0, explanation: "Hope of." },
		{ sentence: "He is bound ____ fail.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Bound to V (chắc chắn)." },
		{ sentence: "She is sure ____ pass.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Sure to V." },
		{ sentence: "It is certain ____ rain.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Certain to V." },
		{ sentence: "He is likely ____ come.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Likely to V." },
		{ sentence: "The chances ____ winning are small.", options: ["of", "to", "for", "in"], correct: 0, explanation: "Chances of." },
		{ sentence: "I have a good mind ____ leave.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Have a good mind to V." },
		{ sentence: "I made up my mind ____ stay.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Make up mind to V." },
		{ sentence: "She set her heart ____ winning.", options: ["on", "in", "to", "of"], correct: 0, explanation: "Set heart on V-ing." },
		{ sentence: "He put an end ____ the war.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Put an end to." },
		{ sentence: "She paid attention ____ the teacher.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Pay attention to." },
		{ sentence: "He took advantage ____ the situation.", options: ["of", "to", "for", "in"], correct: 0, explanation: "Take advantage of." },
		{ sentence: "We caught sight ____ the ship.", options: ["of", "to", "for", "in"], correct: 0, explanation: "Catch sight of." },
		{ sentence: "He lost sight ____ his goal.", options: ["of", "to", "for", "in"], correct: 0, explanation: "Lose sight of." },
		{ sentence: "Make room ____ the new sofa.", options: ["for", "to", "of", "in"], correct: 0, explanation: "Make room for." },
		{ sentence: "Keep an eye ____ the baby.", options: ["on", "in", "at", "for"], correct: 0, explanation: "Keep an eye on." },
		{ sentence: "He lost his temper ____ me.", options: ["with", "to", "at", "for"], correct: 0, explanation: "Lose temper with." },
		{ sentence: "She burst ____ tears.", options: ["into", "out", "in", "on"], correct: 0, explanation: "Burst into tears." },
		{ sentence: "He burst out ____.", options: ["laughing", "to laugh", "laugh", "laughed"], correct: 0, explanation: "Burst out V-ing." },
		{ sentence: "She is prone ____ accidents.", options: ["to", "of", "for", "in"], correct: 0, explanation: "Prone to." },
		{ sentence: "He is liable ____ tax.", options: ["for", "to", "of", "in"], correct: 1, explanation: "Liable to (có khả năng bị) / Liable for (chịu trách nhiệm về)." },
		{ sentence: "I am obliged ____ you.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Obliged to." },
		{ sentence: "He is resigned ____ his fate.", options: ["to", "for", "with", "of"], correct: 0, explanation: "Resigned to (chấp nhận)." },
		{ sentence: "It resulted ____ a failure.", options: ["in", "from", "to", "of"], correct: 0, explanation: "Result in." },
		{ sentence: "Poverty results ____ laziness.", options: ["from", "in", "to", "of"], correct: 0, explanation: "Result from." },
		{ sentence: "He suffers ____ asthma.", options: ["from", "of", "with", "in"], correct: 0, explanation: "Suffer from." },
		{ sentence: "Don't interfere ____ my business.", options: ["in", "with", "to", "of"], correct: 0, explanation: "Interfere in/with." },
	],
	C2: [
		{ sentence: "Had it not been for the alarm, I ____ slept.", options: ["would have", "would", "had", "will have"], correct: 0, explanation: "Đảo ngữ câu điều kiện loại 3 (Had it not been for)." },
		{ sentence: "So great ____ the demand that we sold out.", options: ["was", "is", "did", "were"], correct: 0, explanation: "Đảo ngữ với So + adj." },
		{ sentence: "Such ____ the noise that I couldn't hear.", options: ["was", "is", "did", "were"], correct: 0, explanation: "Đảo ngữ với Such + be + N." },
		{ sentence: "Rarely ____ visited by such a dignitary.", options: ["have we been", "we have been", "did we be", "we were"], correct: 0, explanation: "Đảo ngữ với Rarely (passive)." },
		{ sentence: "Not for a moment ____ I suspect him.", options: ["did", "do", "have", "am"], correct: 0, explanation: "Đảo ngữ Not for a moment." },
		{ sentence: "Only when ____ the report did I understand.", options: ["I had read", "I read", "did I read", "had I read"], correct: 0, explanation: "Only when + clause (normal order) + auxiliary + S + V." },
		{ sentence: "____ I to accept the offer, I would move.", options: ["Were", "Was", "If", "Had"], correct: 0, explanation: "Đảo ngữ điều kiện loại 2: Were + S + to V." },
		{ sentence: "Should you ____ change your mind, let me know.", options: ["happen to", "happened to", "happens to", "happening to"], correct: 0, explanation: "Should you happen to V." },
		{ sentence: "If I ____ to have known, I would have acted.", options: ["was", "were", "am", "had"], correct: 1, explanation: "If I were to have known (hypothetical past)." },
		{ sentence: "Suppose he ____ you, what would you say?", options: ["asking", "asked", "ask", "asks"], correct: 1, explanation: "Suppose (that) he asked (hypothetical)." },
		{ sentence: "It is essential that he ____ immediately.", options: ["be informed", "is informed", "was informed", "informed"], correct: 0, explanation: "Subjunctive passive: be informed." },
		{ sentence: "I proposed that the meeting ____ postponed.", options: ["be", "is", "was", "been"], correct: 0, explanation: "Subjunctive passive." },
		{ sentence: "The building is reported ____ destroyed.", options: ["to have been", "to be", "having been", "being"], correct: 0, explanation: "Passive infinitive perfect: to have been V3." },
		{ sentence: "He is said ____ working on a new book.", options: ["to be", "to have been", "being", "having been"], correct: 0, explanation: "Passive infinitive continuous." },
		{ sentence: "She is alleged ____ the money.", options: ["to have stolen", "staling", "stolen", "steal"], correct: 0, explanation: "Passive infinitive perfect." },
		{ sentence: "There is no ____ what will happen.", options: ["knowing", "knowledge", "know", "known"], correct: 0, explanation: "There is no knowing." },
		{ sentence: "It goes without ____ that health is wealth.", options: ["saying", "say", "said", "to say"], correct: 0, explanation: "It goes without saying." },
		{ sentence: "I can't help but ____.", options: ["wonder", "wondering", "to wonder", "wondered"], correct: 0, explanation: "Can't help but + V (nguyên thể)." },
		{ sentence: "I would rather you ____ yesterday.", options: ["hadn't called", "didn't call", "not call", "don't call"], correct: 0, explanation: "Would rather + S + QKHT (trái với quá khứ)." },
		{ sentence: "It is time you ____ home.", options: ["went", "go", "gone", "going"], correct: 0, explanation: "It is time + past subjunctive." },
		{ sentence: "I prefer ____ rather than watch TV.", options: ["to read", "reading", "read", "reads"], correct: 0, explanation: "Prefer to V rather than V." },
		{ sentence: "He objects to ____ like a child.", options: ["being treated", "treat", "treating", "be treated"], correct: 0, explanation: "Object to + V-ing (passive)." },
		{ sentence: "I look forward to ____ acceptable.", options: ["being considered", "consider", "considering", "be considered"], correct: 0, explanation: "Look forward to being V3." },
		{ sentence: "Despite ____ elected, he resigned.", options: ["having been", "being", "been", "have been"], correct: 0, explanation: "Perfect participle passive: Having been V3." },
		{ sentence: "____ warned, he persisted.", options: ["Having been", "Being", "Been", "Have been"], correct: 0, explanation: "Perfect participle passive." },
		{ sentence: "Buying a house involves ____ a mortgage.", options: ["getting", "to get", "get", "got"], correct: 0, explanation: "Involve + V-ing." },
		{ sentence: "It is no use ____ over spilt milk.", options: ["crying", "cry", "to cry", "cried"], correct: 0, explanation: "Idiom." },
		{ sentence: "There's no point ____ him.", options: ["asking", "ask", "to ask", "asked"], correct: 0, explanation: "There is no point asking." },
		{ sentence: "It is worth ____ a try.", options: ["giving", "give", "to give", "given"], correct: 0, explanation: "Worth giving." },
		{ sentence: "I have trouble ____ my keys.", options: ["finding", "find", "to find", "found"], correct: 0, explanation: "Have trouble V-ing." },
		{ sentence: "She admitted ____ a mistake.", options: ["having made", "making", "make", "made"], correct: 0, explanation: "Admit having V3 (emphasis on completeness)." },
		{ sentence: "He denied ____ the crime.", options: ["having committed", "committing", "commit", "committed"], correct: 0, explanation: "Deny having V3." },
		{ sentence: "I regret ____ your feelings.", options: ["having hurt", "hurting", "hurt", "to hurt"], correct: 0, explanation: "Regret having V3." },
		{ sentence: "He was accused of ____ documents.", options: ["having forged", "forging", "forge", "forged"], correct: 0, explanation: "Accused of having V3." },
		{ sentence: "____ the work, he rested.", options: ["Having done", "Doing", "Done", "Do"], correct: 0, explanation: "Having done (active)." },
		{ sentence: "The book, ____ in 1990, is a classic.", options: ["written", "writing", "wrote", "write"], correct: 0, explanation: "Past participle phrase." },
		{ sentence: "The man ____ over there is my boss.", options: ["standing", "stood", "stands", "stand"], correct: 0, explanation: "Present participle phrase." },
		{ sentence: "Strictly ____, spiders are not insects.", options: ["speaking", "speak", "spoken", "spoke"], correct: 0, explanation: "Strictly speaking." },
		{ sentence: "Granted that he is old, ____ he is strong.", options: ["yet", "so", "but", "and"], correct: 0, explanation: "Granted that ... yet ..." },
		{ sentence: "Seeing that you are here, ____ start.", options: ["let's", "we", "shall", "will"], correct: 0, explanation: "Seeing that (Considering that)." },
		{ sentence: "Given the circumstances, we ____ wait.", options: ["must", "can", "shall", "will"], correct: 0, explanation: "Given the circumstances." },
		{ sentence: "____ for his help, I would have failed.", options: ["But", "If", "Only", "Except"], correct: 0, explanation: "But for." },
		{ sentence: "____ I known, I would have come.", options: ["Had", "If", "Did", "Have"], correct: 0, explanation: "Had I known." },
		{ sentence: "On no account ____ you tell him.", options: ["must", "should", "do", "have"], correct: 0, explanation: "On no account must you." },
		{ sentence: "Whatever the reason ____ be, I don't care.", options: ["may", "can", "will", "must"], correct: 0, explanation: "Whatever the reason may be." },
		{ sentence: "Be that ____, I disagree.", options: ["as it may", "so", "if", "when"], correct: 0, explanation: "Be that as it may." },
		{ sentence: "Come ____ may, I'll stay.", options: ["what", "when", "who", "which"], correct: 0, explanation: "Come what may." },
		{ sentence: "____ it to say, he failed.", options: ["Suffice", "Suffices", "Sufficed", "Sufficing"], correct: 0, explanation: "Suffice it to say." },
		{ sentence: "God ____ you!", options: ["bless", "blesses", "blessed", "blessing"], correct: 0, explanation: "God bless." },
		{ sentence: "Long ____ the King!", options: ["live", "lives", "lived", "living"], correct: 0, explanation: "Long live." },
		{ sentence: "I suggest he ____ a doctor.", options: ["see", "sees", "seen", "saw"], correct: 0, explanation: "Suggest he see (subjunctive)." },
		{ sentence: "If need ____, I'll go.", options: ["be", "is", "was", "were"], correct: 0, explanation: "If need be." },
		{ sentence: "As it ____, we are winning.", options: ["were", "is", "was", "be"], correct: 0, explanation: "As it were (idiom: so to speak)." },
		{ sentence: "If I were ____ fly, I would.", options: ["to", "for", "with", "at"], correct: 0, explanation: "If I were to fly." },
		{ sentence: "Suppose you ____ won, what then?", options: ["had", "have", "has", "did"], correct: 0, explanation: "Suppose you had won (past hypothetical)." },
		{ sentence: "I wish I ____ born rich.", options: ["had been", "was", "were", "have been"], correct: 0, explanation: "Wish had been." },
		{ sentence: "If only I ____ listened.", options: ["had", "have", "did", "was"], correct: 0, explanation: "If only I had." },
		{ sentence: "I prefer that he ____ nothing.", options: ["do", "does", "did", "done"], correct: 0, explanation: "Prefer that he do (subjunctive)." },
		{ sentence: "Request that she ____ allowed.", options: ["be", "is", "was", "been"], correct: 0, explanation: "Request that she be." },
		{ sentence: "It is vital that he ____ informed.", options: ["be", "is", "was", "been"], correct: 0, explanation: "Vital that he be." },
		{ sentence: "Lest he ____ forget, remind him.", options: ["should", "would", "could", "might"], correct: 0, explanation: "Lest he should." },
		{ sentence: "For fear that he ____ fall.", options: ["might", "will", "can", "may"], correct: 0, explanation: "For fear that he might." },
		{ sentence: "Whether it ____ true or not, it's funny.", options: ["be", "is", "was", "were"], correct: 0, explanation: "Whether it be (subjunctive)." },
		{ sentence: "Truth ____ told, I hate it.", options: ["be", "is", "was", "were"], correct: 0, explanation: "Truth be told." },
		{ sentence: "Far ____ it from me to criticize.", options: ["be", "is", "was", "were"], correct: 0, explanation: "Far be it from me." },
		{ sentence: "____ it so.", options: ["So be", "Be so", "Is so", "So is"], correct: 0, explanation: "So be it." },
		{ sentence: "Manner ____, he is rude.", options: ["aside", "apart", "away", "off"], correct: 0, explanation: "Manner aside (Gác chuyện thái độ sang một bên)." },
		{ sentence: "Joking ____, be serious.", options: ["apart", "aside", "away", "off"], correct: 0, explanation: "Joking apart/aside." },
		{ sentence: "All things ____, it's good.", options: ["considered", "considering", "consider", "considers"], correct: 0, explanation: "All things considered." },
		{ sentence: "That ____ said, I agree.", options: ["being", "been", "be", "is"], correct: 0, explanation: "That being said." },
		{ sentence: "Weather ____, we'll go.", options: ["permitting", "permits", "permitted", "permit"], correct: 0, explanation: "Weather permitting." },
		{ sentence: "God ____, we will succeed.", options: ["willing", "wills", "willed", "will"], correct: 0, explanation: "God willing." },
		{ sentence: "Not ____ the point, but...", options: ["to labour", "labouring", "labour", "laboured"], correct: 0, explanation: "Not to labour the point." },
		{ sentence: "To ____ it mildly, it was bad.", options: ["put", "say", "tell", "speak"], correct: 0, explanation: "To put it mildly." },
		{ sentence: "Needless ____, he failed.", options: ["to say", "saying", "say", "said"], correct: 0, explanation: "Needless to say." },
		{ sentence: "Whatever the cost ____ be, do it.", options: ["may", "will", "can", "shall"], correct: 0, explanation: "Whatever ... may be." },
		{ sentence: "However hard it ____ be, try.", options: ["may", "will", "can", "shall"], correct: 0, explanation: "However ... may be." },
		{ sentence: "Strange ____ it sounds, it's true.", options: ["as", "so", "though", "if"], correct: 0, explanation: "Strange as it sounds." },
		{ sentence: "Hard ____ it was, we won.", options: ["as", "so", "though", "if"], correct: 0, explanation: "Hard as it was." },
		{ sentence: "Try ____ I might, I failed.", options: ["as", "so", "though", "if"], correct: 0, explanation: "Try as I might." },
		{ sentence: "Much ____ I like you, leaving.", options: ["as", "so", "though", "if"], correct: 0, explanation: "Much as I like you." },
		{ sentence: "____ that as it may.", options: ["Be", "Is", "Was", "Were"], correct: 0, explanation: "Be that as it may." },
		{ sentence: "____ you require help, call.", options: ["Should", "If", "Do", "have"], correct: 0, explanation: "Should you." },
		{ sentence: "____ I be of service?", options: ["May", "Can", "Will", "Shall"], correct: 0, explanation: "May I be." },
		{ sentence: "If it ____ for him, I'd be dead.", options: ["weren't", "wasn't", "isn't", "aren't"], correct: 0, explanation: "If it weren't for." },
		{ sentence: "If it ____ been for him...", options: ["hadn't", "hasn't", "didn't", "wouldn't"], correct: 0, explanation: "If it hadn't been for." },
		{ sentence: "I would have lost ____ but for his help.", options: ["everything", "nothing", "anything", "something"], correct: 0, explanation: "But for + Noun phrase (If it hadn't been for)." },
		{ sentence: "Let's assume ____ sake of argument.", options: ["for the", "for", "to the", "with the"], correct: 0, explanation: "For the sake of argument." },
		{ sentence: "By ____ of explanation, look here.", options: ["way", "means", "virtue", "reason"], correct: 0, explanation: "By way of explanation." },
		{ sentence: "On ____ of his health, he quit.", options: ["account", "reason", "sake", "behalf"], correct: 0, explanation: "On account of." },
		{ sentence: "With ____ to your letter, I reply.", options: ["reference", "regard", "respect", "relation"], correct: 0, explanation: "With reference to." },
		{ sentence: "With ____ to costs, it's high.", options: ["regard", "reference", "respect", "relation"], correct: 0, explanation: "With regard to." },
		{ sentence: "In ____ of the law, he acted.", options: ["view", "light", "sight", "spite"], correct: 0, explanation: "In view of." },
		{ sentence: "In ____ with the rules, do this.", options: ["accordance", "accord", "according", "accords"], correct: 0, explanation: "In accordance with." },
		{ sentence: "For the ____ of clarity, I repeat.", options: ["sake", "good", "benefit", "reason"], correct: 0, explanation: "For the sake of." },
		{ sentence: "At the ____ of his career, he died.", options: ["peak", "top", "height", "point"], correct: 0, explanation: "At the peak/height. Both fit but 'peak' is common." },
		{ sentence: "On the ____ of collapse, he fell.", options: ["verge", "edge", "brink", "point"], correct: 0, explanation: "On the verge of." },
		{ sentence: "On the ____ of extinction.", options: ["brink", "edge", "verge", "point"], correct: 0, explanation: "On the brink of." },
		{ sentence: "In the ____ of danger, stay calm.", options: ["face", "teeth", "eyes", "hands"], correct: 0, explanation: "In the face of." },
		{ sentence: "In ____ of his efforts, he failed.", options: ["spite", "despite", "view", "light"], correct: 0, explanation: "In spite of." },
		{ sentence: "To the ____ of my knowledge.", options: ["best", "good", "better", "well"], correct: 0, explanation: "To the best of my knowledge." },
	],
};

export default questions;
