export const IRREGULAR_VERBS: Record<string, string> = {
  was: "be",
  were: "be",
  been: "be",
  being: "be",
  am: "be",
  is: "be",
  are: "be",
  had: "have",
  has: "have",
  having: "have",
  did: "do",
  does: "do",
  doing: "do",
  done: "do",
  went: "go",
  gone: "go",
  going: "go",
  got: "get",
  gotten: "get",
  getting: "get",
  made: "make",
  making: "make",
  took: "take",
  taken: "take",
  taking: "take",
  came: "come",
  coming: "come",
  saw: "see",
  seen: "see",
  seeing: "see",
  knew: "know",
  known: "know",
  knowing: "know",
  gave: "give",
  given: "give",
  giving: "give",
  found: "find",
  finding: "find",
  told: "tell",
  telling: "tell",
  felt: "feel",
  feeling: "feel",
  became: "become",
  becoming: "become",
  left: "leave",
  leaving: "leave",
  brought: "bring",
  bringing: "bring",
  used: "use",
  using: "use",
  uses: "use",
  began: "begin",
  begun: "begin",
  beginning: "begin",
  kept: "keep",
  keeping: "keep",
  held: "hold",
  holding: "hold",
  wrote: "write",
  written: "write",
  writing: "write",
  stood: "stand",
  standing: "stand",
  heard: "hear",
  hearing: "hear",
  let: "let",
  letting: "let",
  meant: "mean",
  meaning: "mean",
  set: "set",
  setting: "set",
  met: "meet",
  meeting: "meet",
  ran: "run",
  running: "run",
  paid: "pay",
  paying: "pay",
  sat: "sit",
  sitting: "sit",
  spoke: "speak",
  spoken: "speak",
  speaking: "speak",
  lay: "lie",
  lain: "lie",
  lying: "lie",
  led: "lead",
  leading: "lead",
  read: "read",
  reading: "read",
  grew: "grow",
  grown: "grow",
  growing: "grow",
  fell: "fall",
  fallen: "fall",
  falling: "fall",
  sent: "send",
  sending: "send",
  built: "build",
  building: "build",
  understood: "understand",
  understanding: "understand",
  drew: "draw",
  drawn: "draw",
  drawing: "draw",
  bought: "buy",
  buying: "buy",
  spent: "spend",
  spending: "spend",
  cut: "cut",
  cutting: "cut",
  arose: "arise",
  arisen: "arise",
  arising: "arise",
  awoke: "awake",
  awoken: "awake",
  awaking: "awake",
  bore: "bear",
  born: "bear",
  bearing: "bear",
  beat: "beat",
  beaten: "beat",
  beating: "beat",
  bent: "bend",
  bending: "bend",
  bit: "bite",
  bitten: "bite",
  biting: "bite",
  bled: "bleed",
  bleeding: "bleed",
  blew: "blow",
  blown: "blow",
  blowing: "blow",
  broke: "break",
  broken: "break",
  breaking: "break",
  bred: "breed",
  breeding: "breed",
  burnt: "burn",
  burned: "burn",
  burning: "burn",
  burst: "burst",
  bursting: "burst",
  caught: "catch",
  catching: "catch",
  chose: "choose",
  chosen: "choose",
  choosing: "choose",
  clung: "cling",
  clinging: "cling",
  crept: "creep",
  creeping: "creep",
  dealt: "deal",
  dealing: "deal",
  dug: "dig",
  digging: "dig",
  dove: "dive",
  diving: "dive",
  drank: "drink",
  drunk: "drink",
  drinking: "drink",
  drove: "drive",
  driven: "drive",
  driving: "drive",
  ate: "eat",
  eaten: "eat",
  eating: "eat",
  fed: "feed",
  feeding: "feed",
  fought: "fight",
  fighting: "fight",
  fled: "flee",
  fleeing: "flee",
  flew: "fly",
  flown: "fly",
  flying: "fly",
  forbade: "forbid",
  forbidden: "forbid",
  forbidding: "forbid",
  forgot: "forget",
  forgotten: "forget",
  forgetting: "forget",
  forgave: "forgive",
  forgiven: "forgive",
  forgiving: "forgive",
  froze: "freeze",
  frozen: "freeze",
  freezing: "freeze",
  hid: "hide",
  hidden: "hide",
  hiding: "hide",
  hit: "hit",
  hitting: "hit",
  hung: "hang",
  hanging: "hang",
  hurt: "hurt",
  hurting: "hurt",
  knelt: "kneel",
  kneeling: "kneel",
  laid: "lay",
  laying: "lay",
  learnt: "learn",
  learned: "learn",
  learning: "learn",
  lit: "light",
  lighting: "light",
  lost: "lose",
  losing: "lose",
  rode: "ride",
  ridden: "ride",
  riding: "ride",
  rang: "ring",
  rung: "ring",
  ringing: "ring",
  rose: "rise",
  risen: "rise",
  rising: "rise",
  sang: "sing",
  sung: "sing",
  singing: "sing",
  sank: "sink",
  sunk: "sink",
  sinking: "sink",
  slept: "sleep",
  sleeping: "sleep",
  slid: "slide",
  sliding: "slide",
  slung: "sling",
  slinging: "sling",
  slit: "slit",
  slitting: "slit",
  smelt: "smell",
  smelling: "smell",
  sowed: "sow",
  sown: "sow",
  sowing: "sow",
  sped: "speed",
  speeding: "speed",
  spelt: "spell",
  spelled: "spell",
  spelling: "spell",
  spilt: "spill",
  spilled: "spill",
  spilling: "spill",
  spun: "spin",
  spinning: "spin",
  spat: "spit",
  spitting: "spit",
  split: "split",
  splitting: "split",
  spread: "spread",
  spreading: "spread",
  sprang: "spring",
  sprung: "spring",
  springing: "spring",
  stole: "steal",
  stolen: "steal",
  stealing: "steal",
  stuck: "stick",
  sticking: "stick",
  stung: "sting",
  stinging: "sting",
  stank: "stink",
  stunk: "stink",
  stinking: "stink",
  strode: "stride",
  striding: "stride",
  struck: "strike",
  stricken: "strike",
  striking: "strike",
  strove: "strive",
  striven: "strive",
  striving: "strive",
  swore: "swear",
  sworn: "swear",
  swearing: "swear",
  swept: "sweep",
  sweeping: "sweep",
  swam: "swim",
  swum: "swim",
  swimming: "swim",
  swung: "swing",
  swinging: "swing",
  taught: "teach",
  teaching: "teach",
  tore: "tear",
  torn: "tear",
  tearing: "tear",
  threw: "throw",
  thrown: "throw",
  throwing: "throw",
  thought: "think",
  thinking: "think",
  trod: "tread",
  trodden: "tread",
  treading: "tread",
  woke: "wake",
  woken: "wake",
  waking: "wake",
  wore: "wear",
  worn: "wear",
  wearing: "wear",
  wove: "weave",
  woven: "weave",
  weaving: "weave",
  wept: "weep",
  weeping: "weep",
  won: "win",
  winning: "win",
  wound: "wind",
  winding: "wind",
  withdrew: "withdraw",
  withdrawn: "withdraw",
  withdrawing: "withdraw",
  wrung: "wring",
  wringing: "wring",
};

// Words ending in -ed or -ing that are base words (e.g. adjectives, nouns)
// and should not have their suffixes stripped down to verbs.
export const DO_NOT_STEM = new Set([
  "sophisticated",
  "complicated",
  "dedicated",
  "detailed",
  "limited",
  "related",
  "associated",
  "united",
  "required",
  "advanced",
  "tired",
  "excited",
  "interested",
  "bored",
  "naked",
  "sacred",
  "wicked",
  "rugged",
  "wretched",
  "beloved",
  "crooked",
  "blessed",
  "learned",
  "aged",
  "dogged",
  "ragged",
  "jagged",
  "unprecedented",
  "during",
  "meaning",
  "something",
  "nothing",
  "anything",
  "everything",
  "morning",
  "evening",
  "wedding",
  "building",
  "ceiling",
  "reading",
  "listening",
  "speaking",
  "writing",
  "learning",
  "training",
  "understanding",
  "marketing",
  "meeting",
  "clothing",
  "engineering",
  "well-being",
  "being",
  "sometimes",
  "always",
  "perhaps",
  "spontaneous",
  "downstairs",
  "upstairs",
  "news",
]);
