export const IRREGULAR_PLURALS: Record<string, string> = {
  children: "child",
  people: "person",
  men: "man",
  women: "woman",
  mice: "mouse",
  geese: "goose",
  teeth: "tooth",
  feet: "foot",
  oxen: "ox",
};

// Words that are always plural (pluralia tantum)
export const ALWAYS_PLURAL = new Set([
  "pants",
  "trousers",
  "jeans",
  "shorts",
  "glasses",
  "spectacles",
  "goggles",
  "scissors",
  "pliers",
  "tongs",
  "tweezers",
  "binoculars",
  "thanks",
  "clothes",
  "credentials",
  "earnings",
  "goods",
  "premises",
  "riches",
  "stairs",
  "surroundings",
  "belongings",
  // Academic subjects and fields ending in -ics
  "genetics",
  "physics",
  "mathematics",
  "maths",
  "economics",
  "statistics",
  "politics",
  "ethics",
  "linguistics",
  "phonetics",
  "athletics",
  "gymnastics",
  "electronics",
  "mechanics",
  "dynamics",
  "aerodynamics",
  "thermodynamics",
  "acoustics",
  "optics",
  "robotics",
  "bionics",
  "ceramics",
  "classics",
  "graphics",
  "pediatrics",
  "obstetrics",
  "orthopedics",
  "geriatrics",
  "sometimes",
  "always",
  "news",
]);
