import { LevelListeningData } from "../types";

export const C2_LISTENING: LevelListeningData = {
    dictations: [
        {
            id: "c2-dict-1",
            title: "Ontological Uncertainty",
            level: "C2",
            content: "The philosopher's discourse on ontological uncertainty challenged the very foundations of contemporary metaphysical assumptions.",
            answer: "The philosopher's discourse on ontological uncertainty challenged the very foundations of contemporary metaphysical assumptions.",
        },
        {
            id: "c2-dict-2",
            title: "Epistemological Relativism",
            level: "C2",
            content: "Critics of epistemological relativism argue that it inevitably leads to a state of intellectual nihilism and the erosion of objective truth.",
            answer: "Critics of epistemological relativism argue that it inevitably leads to a state of intellectual nihilism and the erosion of objective truth.",
        },
        {
            id: "c2-dict-3",
            title: "Socio-Political Fragmentation",
            level: "C2",
            content: "The pervasive socio-political fragmentation observed in urban centers is often exacerbated by the echo chambers of digital discourse.",
            answer: "The pervasive socio-political fragmentation observed in urban centers is often exacerbated by the echo chambers of digital discourse.",
        },
        {
            id: "c2-dict-4",
            title: "Biotechnological Convergence",
            level: "C2",
            content: "The unprecedented biotechnological convergence witnessed today necessitates a radical reevaluation of our ethical and legal frameworks.",
            answer: "The unprecedented biotechnological convergence witnessed today necessitates a radical reevaluation of our ethical and legal frameworks.",
        },
        {
            id: "c2-dict-5",
            title: "Linguistic Indeterminacy",
            level: "C2",
            content: "Translation is inherently a process of negotiation, as it must navigate the treacherous waters of linguistic indeterminacy and cultural nuance.",
            answer: "Translation is inherently a process of negotiation, as it must navigate the treacherous waters of linguistic indeterminacy and cultural nuance.",
        },
        {
            id: "c2-dict-6",
            title: "Technocratic Hegemony",
            level: "C2",
            content: "The rise of technocratic hegemony has sparked vigorous debate regarding the potential obsolescence of traditional democratic participation.",
            answer: "The rise of technocratic hegemony has sparked vigorous debate regarding the potential obsolescence of traditional democratic participation.",
        },
        {
            id: "c2-dict-7",
            title: "Axiomatic Assumptions",
            level: "C2",
            content: "Mathematics relies on a series of axiomatic assumptions that, while seemingly intuitive, form the bedrock of all logical deduction.",
            answer: "Mathematics relies on a series of axiomatic assumptions that, while seemingly intuitive, form the bedrock of all logical deduction.",
        },
        {
            id: "c2-dict-8",
            title: "Psychological Subterfuge",
            level: "C2",
            content: "The narrative expertly employs psychological subterfuge to keep the reader in a state of perpetual suspense until the final denouement.",
            answer: "The narrative expertly employs psychological subterfuge to keep the reader in a state of perpetual suspense until the final denouement.",
        },
        {
            id: "c2-dict-9",
            title: "Environmental Catastrophism",
            level: "C2",
            content: "While environmental catastrophism is often criticized for being alarmist, it highlights the undeniable urgency of the current ecological crisis.",
            answer: "While environmental catastrophism is often criticized for being alarmist, it highlights the undeniable urgency of the current ecological crisis.",
        },
        {
            id: "c2-dict-10",
            title: "Intertextual Allusions",
            level: "C2",
            content: "The poet's work is renowned for its dense intertextual allusions, requiring a profound knowledge of classical literature to fully decipher.",
            answer: "The poet's work is renowned for its dense intertextual allusions, requiring a profound knowledge of classical literature to fully decipher.",
        },
        {
            id: "c2-dict-11",
            title: "Macro-Economic Volatility",
            level: "C2",
            content: "The persistent macro-economic volatility in emerging markets can be attributed to a idiosyncratic combination of domestic and global factors.",
            answer: "The persistent macro-economic volatility in emerging markets can be attributed to a idiosyncratic combination of domestic and global factors.",
        },
        {
            id: "c2-dict-12",
            title: "Institutional Inertia",
            level: "C2",
            content: "Overcoming institutional inertia is often the most formidable obstacle to implementing much-needed reforms in large organizations.",
            answer: "Overcoming institutional inertia is often the most formidable obstacle to implementing much-needed reforms in large organizations.",
        },
        {
            id: "c2-dict-13",
            title: "Phenomenological Experience",
            level: "C2",
            content: "The study aims to provide a comprehensive analysis of the phenomenological experience of time in patients with specific neural deficits.",
            answer: "The study aims to provide a comprehensive analysis of the phenomenological experience of time in patients with specific neural deficits.",
        },
        {
            id: "c2-dict-14",
            title: "Constitutional Jurisprudence",
            level: "C2",
            content: "The evolution of constitutional jurisprudence reflects the changing societal values and the constant tension between individual and state.",
            answer: "The evolution of constitutional jurisprudence reflects the changing societal values and the constant tension between individual and state.",
        },
        {
            id: "c2-dict-15",
            title: "Aesthetic Subjectivity",
            level: "C2",
            content: "The elusive nature of aesthetic subjectivity ensures that the interpretation of a masterpiece will invariably differ among individuals.",
            answer: "The elusive nature of aesthetic subjectivity ensures that the interpretation of a masterpiece will invariably differ among individuals.",
        },
        {
            id: "c2-dict-16",
            title: "Technological Singularity",
            level: "C2",
            content: "The concept of a technological singularity describes a point beyond which human history is fundamentally altered by superintelligence.",
            answer: "The concept of a technological singularity describes a point beyond which human history is fundamentally altered by superintelligence.",
        },
        {
            id: "c2-dict-17",
            title: "Inherent Contradictions",
            level: "C2",
            content: "The author meticulously deconstructs the inherent contradictions within the prevailing economic paradigm of the late twentieth century.",
            answer: "The author meticulously deconstructs the inherent contradictions within the prevailing economic paradigm of the late twentieth century.",
        },
        {
            id: "c2-dict-18",
            title: "Existential Authenticity",
            level: "C2",
            content: "Finding existential authenticity in a world defined by superficiality is a recurring theme in the works of many contemporary novelists.",
            answer: "Finding existential authenticity in a world defined by superficiality is a recurring theme in the works of many contemporary novelists.",
        },
        {
            id: "c2-dict-19",
            title: "Ecosystem Fragility",
            level: "C2",
            content: "The alarming rate of species extinction underscores the extreme ecosystem fragility in regions subjected to intensive deforestation.",
            answer: "The alarming rate of species extinction underscores the extreme ecosystem fragility in regions subjected to intensive deforestation.",
        },
        {
            id: "c2-dict-20",
            title: "Judicial Prerogative",
            level: "C2",
            content: "The extent of judicial prerogative in interpreting legislative intent remains a subject of intense debate among legal scholars.",
            answer: "The extent of judicial prerogative in interpreting legislative intent remains a subject of intense debate among legal scholars.",
        },
    ],
    comprehensions: [
        {
            id: "c2-comp-1",
            title: "The Quagmire of Consciousness",
            level: "C2",
            content: "The 'hard problem' of consciousness remains the most formidable frontier in contemporary philosophy of mind. While neurobiology can elucidate the 'easy problems'—the functional mechanisms of information processing and behavioral response—it fails to bridge the 'explanatory gap' between physical neural firings and the internal, subjective quality of experience, or 'qualia.' Some proponents of panpsychism suggest that consciousness might be a fundamental property of the universe, akin to mass or charge, while eliminative materialists argue that our intuitive understanding of the mind is a flawed 'folk psychology' that will eventually be replaced by a purely neuroscientific account. This ongoing debate touches upon our deepest conceptions of reality, selfhood, and the limits of scientific explanation.",
            transcript: "The 'hard problem' of consciousness remains the most formidable frontier in contemporary philosophy of mind. While neurobiology can elucidate the 'easy problems'—the functional mechanisms of information processing and behavioral response—it fails to bridge the 'explanatory gap' between physical neural firings and the internal, subjective quality of experience, or 'qualia.' Some proponents of panpsychism suggest that consciousness might be a fundamental property of the universe, akin to mass or charge, while eliminative materialists argue that our intuitive understanding of the mind is a flawed 'folk psychology' that will eventually be replaced by a purely neuroscientific account. This ongoing debate touches upon our deepest conceptions of reality, selfhood, and the limits of scientific explanation.",
            questions: [
                {
                    question: "What is the 'hard problem' of consciousness as defined in the text?",
                    options: ["Understanding how neurons fire", "Bridging the gap between physical processes and subjective experience", "Learning how the brain processes language", "Mapping the entire human genome"],
                    correct: 1,
                    explanation: "In the passage: 'fails to bridge the 'explanatory gap' between physical neural firings and the internal, subjective quality of experience...'",
                },
                {
                    question: "How do 'easy problems' differ from the 'hard problem'?",
                    options: ["They are about emotions", "They concern functional mechanisms and behavior", "They require no science", "They have already been solved"],
                    correct: 1,
                    explanation: "In the passage: ''easy problems'—the functional mechanisms of information processing and behavioral response...'",
                },
                {
                    question: "What are 'qualia'?",
                    options: ["Physical brain regions", "The subjective qualities of experience", "Mathematical constants", "A type of neurotransmitter"],
                    correct: 1,
                    explanation: "The text defines qualia as 'the internal, subjective quality of experience.'",
                },
                {
                    question: "What does panpsychism propose?",
                    options: ["Consciousness is an illusion", "Consciousness is a fundamental property of the universe", "Only humans have consciousness", "Computers will never be conscious"],
                    correct: 1,
                    explanation: "In the passage: 'suggest that consciousness might be a fundamental property of the universe...'",
                },
                {
                    question: "What is the central claim of eliminative materialism?",
                    options: ["Mind and body are separate", "Current understanding of the mind is flawed 'folk psychology'", "Consciousness is magical", "Religion explains the mind best"],
                    correct: 1,
                    explanation: "In the passage: 'intuitive understanding of the mind is a flawed 'folk psychology' that will eventually be replaced...' ",
                },
                {
                    question: "What does this debate ultimately question?",
                    options: ["The cost of brain surgery", "Conceptions of reality, selfhood, and scientific limits", "The history of the 20th century", "The best way to teach psychology"],
                    correct: 1,
                    explanation: "In the passage: 'touches upon our deepest conceptions of reality, selfhood, and the limits of scientific explanation.'",
                },
            ],
        },
        {
            id: "c2-comp-2",
            title: "The Erosion of Trust in the Post-Truth Era",
            level: "C2",
            content: "The term 'post-truth' describes a political culture where objective facts are less influential in shaping public opinion than appeals to emotion and personal belief. This phenomenon is inextricably linked to the 'fragmentation of the media landscape,' where the proliferation of digital platforms allows individuals to inhabit 'echo chambers' that reinforce their existing world views. In this environment, the very concept of an 'expert' is often delegitimized through a process of 'epistemic closure,' where contradictory evidence is dismissed as part of a perceived conspiratorial agenda. The resulting erosion of social trust poses an existential threat to democratic discourse, which relies on a shared set of verifiable facts for meaningful negotiation and policy-making.",
            transcript: "The term 'post-truth' describes a political culture where objective facts are less influential in shaping public opinion than appeals to emotion and personal belief. This phenomenon is inextricably linked to the 'fragmentation of the media landscape,' where the proliferation of digital platforms allows individuals to inhabit 'echo chambers' that reinforce their existing world views. In this environment, the very concept of an 'expert' is often delegitimized through a process of 'epistemic closure,' where contradictory evidence is dismissed as part of a perceived conspiratorial agenda. The resulting erosion of social trust poses an existential threat to democratic discourse, which relies on a shared set of verifiable facts for meaningful negotiation and policy-making.",
            questions: [
                {
                    question: "What defines a 'post-truth' political culture?",
                    options: ["Strict reliance on data", "Facts are less influential than emotion and belief", "The end of all politics", "A high level of education"],
                    correct: 1,
                    explanation: "In the passage: 'objective facts are less influential... than appeals to emotion and personal belief.'",
                },
                {
                    question: "What is a primary cause of this phenomenon according to the text?",
                    options: ["Lack of books", "Fragmentation of the media landscape", "Space travel", "Better computer security"],
                    correct: 1,
                    explanation: "In the passage: 'inextricably linked to the 'fragmentation of the media landscape...'",
                },
                {
                    question: "What is the function of 'echo chambers'?",
                    options: ["To store audio recordings", "To reinforce existing world views", "To amplify music", "To teach physics students"],
                    correct: 1,
                    explanation: "In the passage: 'echo chambers' that reinforce their existing world views.'",
                },
                {
                    question: "How is the status of 'experts' affected in this era?",
                    options: ["They are paid more", "They are increasingly delegitimized", "They are given more power", "They disappear entirely"],
                    correct: 1,
                    explanation: "In the passage: 'the very concept of an 'expert' is often delegitimized...'",
                },
                {
                    question: "What is 'epistemic closure' as described in the passage?",
                    options: ["Opening up to new ideas", "Closing libraries", "Dismissing contradictory evidence as conspiracy", "A type of locked database"],
                    correct: 2,
                    explanation: "In the passage: 'contradictory evidence is dismissed as part of a perceived conspiratorial agenda.'",
                },
                {
                    question: "Why is the erosion of trust considered an existential threat?",
                    options: ["It makes people sad", "It stops the economy", "Democratic discourse requires shared verifiable facts", "It leads to more crime"],
                    correct: 2,
                    explanation: "In the passage: 'existential threat to democratic discourse, which relies on a shared set of verifiable facts...'",
                },
            ],
        },
        {
            id: "c2-comp-3",
            title: "The Architecture of Deconstruction",
            level: "C2",
            content: "Deconstruction, a philosophical approach pioneered by Jacques Derrida, challenges the 'logocentric' tradition of Western thought—the assumption that there is a central, fixed meaning in language and reality. Instead, deconstruction reveals that all texts are inherently unstable and riddled with 'binary oppositions,' such as speech/writing or presence/absence, where one term is traditionally privileged over the other. By meticulously 'interrogating' a text, deconstructionists demonstrate that the 'marginalized' term is often essential for the meaning of its dominant counterpart. This process does not aim to destroy meaning, but to expose the subtle hierarchies and contradictions that underpin our conceptual frameworks, ultimately suggesting that meaning is always 'deferred' and never fully present.",
            transcript: "Deconstruction, a philosophical approach pioneered by Jacques Derrida, challenges the 'logocentric' tradition of Western thought—the assumption that there is a central, fixed meaning in language and reality. Instead, deconstruction reveals that all texts are inherently unstable and riddled with 'binary oppositions,' such as speech/writing or presence/absence, where one term is traditionally privileged over the other. By meticulously 'interrogating' a text, deconstructionists demonstrate that the 'marginalized' term is often essential for the meaning of its dominant counterpart. This process does not aim to destroy meaning, but to expose the subtle hierarchies and contradictions that underpin our conceptual frameworks, ultimately suggesting that meaning is always 'deferred' and never fully present.",
            questions: [
                {
                    question: "Who is the philosopher associated with deconstruction?",
                    options: ["Kant", "Derrida", "Nietzsche", "Sartre"],
                    correct: 1,
                    explanation: "In the passage: 'pioneered by Jacques Derrida.'",
                },
                {
                    question: "What is the 'logocentric' tradition?",
                    options: ["The study of logos", "The assumption of central, fixed meaning", "A style of architecture", "A preference for logical math"],
                    correct: 1,
                    explanation: "In the passage: 'assumption that there is a central, fixed meaning in language and reality.'",
                },
                {
                    question: "What are 'binary oppositions'?",
                    options: ["Mathematical equations", "Pairs of terms where one is traditionally privileged", "Wars between two countries", "Two people arguing"],
                    correct: 1,
                    explanation: "In the passage: 'binary oppositions... where one term is traditionally privileged over the other.'",
                },
                {
                    question: "What is the goal of 'interrogating' a text in this context?",
                    options: ["To find out who wrote it", "To prove it's wrong", "To expose hierarchies and contradictions", "To summarize it"],
                    correct: 2,
                    explanation: "In the passage: 'expose the subtle hierarchies and contradictions that underpin our conceptual frameworks...'",
                },
                {
                    question: "What does deconstruction suggest about the 'marginalized' term in a binary?",
                    options: ["It is useless", "It is often essential for the dominant term's meaning", "It should be removed", "It is always false"],
                    correct: 1,
                    explanation: "In the passage: 'demonstrate that the 'marginalized' term is often essential for the meaning...'",
                },
                {
                    question: "What is the ultimate characteristic of meaning according to deconstruction?",
                    options: ["Perfectly clear", "Completely absent", "Always deferred", "Owned by the author"],
                    correct: 2,
                    explanation: "In the passage: 'suggesting that meaning is always 'deferred' and never fully present.'",
                },
            ],
        },
        {
            id: "c2-comp-4",
            title: "The Geopolitics of the Deep Sea",
            level: "C2",
            content: "As terrestrial resources dwindle, the deep sea is emerging as the next frontier of geopolitical struggle. The seabed contains vast reserves of 'poly-metallic nodules'—rich in cobalt, nickel, and rare earth elements essential for the green energy transition. However, exploitation of these resources remains a technological and legal challenge. The International Seabed Authority (ISA) is currently struggling to finalize regulations that balance economic interests with the protection of extremely fragile and poorly understood abyssal ecosystems. Furthermore, the lack of clear sovereignty in international waters raises concerns about a new 'scramble for the oceans' that could mirror the historical colonial patterns of terrestrial extraction and trigger conflict among major maritime powers.",
            transcript: "As terrestrial resources dwindle, the deep sea is emerging as the next frontier of geopolitical struggle. The seabed contains vast reserves of 'poly-metallic nodules'—rich in cobalt, nickel, and rare earth elements essential for the green energy transition. However, exploitation of these resources remains a technological and legal challenge. The International Seabed Authority (ISA) is currently struggling to finalize regulations that balance economic interests with the protection of extremely fragile and poorly understood abyssal ecosystems. Furthermore, the lack of clear sovereignty in international waters raises concerns about a new 'scramble for the oceans' that could mirror the historical colonial patterns of terrestrial extraction and trigger conflict among major maritime powers.",
            questions: [
                {
                    question: "Why is the deep sea becoming a geopolitical focus?",
                    options: ["New fish species", "Dwindling terrestrial resources", "Better research ships", "Warfare"],
                    correct: 1,
                    explanation: "In the passage: 'As terrestrial resources dwindle, the deep sea is emerging as the next frontier...'",
                },
                {
                    question: "What are 'poly-metallic nodules'?",
                    options: ["Deep sea plants", "Rocks rich in cobalt and nickel", "A type of shell", "Mechanical sensors"],
                    correct: 1,
                    explanation: "In the passage: 'vast reserves of 'poly-metallic nodules'—rich in cobalt, nickel...'",
                },
                {
                    question: "What is the 'green energy transition' connection mentioned?",
                    options: [" nodules fuel green cars", "nodules contain elements for green technology", "Sea water is used for energy", "Sea air is cleaner"],
                    correct: 1,
                    explanation: "In the passage: 'elements essential for the green energy transition.'",
                },
                {
                    question: "What organization manages international seabed regulations?",
                    options: ["UNICEF", "NATO", "ISA", "NASA"],
                    correct: 2,
                    explanation: "In the passage: 'The International Seabed Authority (ISA) is currently struggling...'",
                },
                {
                    question: "What is the primary ecological concern of deep-sea mining?",
                    options: ["Noise pollution", "Damage to fragile abyssal ecosystems", "Loss of waves", "Too much light"],
                    correct: 1,
                    explanation: "In the passage: 'protection of extremely fragile and poorly understood abyssal ecosystems.'",
                },
                {
                    question: "What historical comparison is made regarding ocean resources?",
                    options: ["The Gold Rush", "The Industrial Revolution", "Colonial patterns of extraction", "The Space Race"],
                    correct: 2,
                    explanation: "In the passage: 'could mirror the historical colonial patterns of terrestrial extraction...'",
                },
            ],
        },
        {
            id: "c2-comp-5",
            title: "The Neuroscience of Aesthetic Perception",
            level: "C2",
            content: "Neuroaesthetics seeks to characterize the biological basis of aesthetic experience, exploring how the brain processes beauty, art, and creativity. A central finding is the involvement of the 'Default Mode Network' (DMN), a brain system typically associated with self-referential thought and internal reflection. When we are deeply moved by an artwork, the DMN becomes highly active, suggesting that aesthetic appreciation is an intensely personal and introspective process. This activity often coincides with the activation of the reward system, releasing dopamine and creating a sense of pleasure. However, the 'aesthetic judgment'—the conscious evaluation of an artwork—also requires the involvement of the executive control networks, highlighting the complex dance between emotional resonance and intellectual scrutiny in the perception of art.",
            transcript: "Neuroaesthetics seeks to characterize the biological basis of aesthetic experience, exploring how the brain processes beauty, art, and creativity. A central finding is the involvement of the 'Default Mode Network' (DMN), a brain system typically associated with self-referential thought and internal reflection. When we are deeply moved by an artwork, the DMN becomes highly active, suggesting that aesthetic appreciation is an intensely personal and introspective process. This activity often coincides with the activation of the reward system, releasing dopamine and creating a sense of pleasure. However, the 'aesthetic judgment'—the conscious evaluation of an artwork—also requires the involvement of the executive control networks, highlighting the complex dance between emotional resonance and intellectual scrutiny in the perception of art.",
            questions: [
                {
                    question: "What is the primary goal of neuroaesthetics?",
                    options: ["Teaching people how to paint", "Characterizing the biological basis of aesthetic experience", "Selling expensive art", "Analyzing history"],
                    correct: 1,
                    explanation: "In the passage: 'seeks to characterize the biological basis of aesthetic experience...'",
                },
                {
                    question: "What brain system is associated with internal reflection and art appreciation?",
                    options: ["Visual Cortex", "Default Mode Network (DMN)", "Limbic System", "Motor Cortex"],
                    correct: 1,
                    explanation: "In the passage: 'involvement of the 'Default Mode Network' (DMN), a brain system typically associated with self-referential thought...'",
                },
                {
                    question: "What does high DMN activity during art viewing suggest?",
                    options: ["Boredom", "Aesthetic appreciation is personal and introspective", "Confusion", "A desire to buy the art"],
                    correct: 1,
                    explanation: "In the passage: 'suggesting that aesthetic appreciation is an intensely personal and introspective process.'",
                },
                {
                    question: "What neurotransmitter is mentioned as part of the pleasure response?",
                    options: ["Serotonin", "Dopamine", "Adrenaline", "Melatonin"],
                    correct: 1,
                    explanation: "In the passage: 'releasing dopamine and creating a sense of pleasure.'",
                },
                {
                    question: "What is 'aesthetic judgment' in this context?",
                    options: ["Feeling sad", "The conscious evaluation of an artwork", "Buying a ticket", "Closing one's eyes"],
                    correct: 1,
                    explanation: "In the passage: ''aesthetic judgment'—the conscious evaluation of an artwork...'",
                },
                {
                    question: "Which networks are involved in the intellectual scrutiny of art?",
                    options: ["Executive control networks", "Smell networks", "Sleep networks", "Muscle networks"],
                    correct: 0,
                    explanation: "In the passage: 'also requires the involvement of the executive control networks...'",
                },
            ],
        },
        {
            id: "c2-comp-6",
            title: "The Paradox of Sustainable Development",
            level: "C2",
            content: "The concept of 'sustainable development' often faces criticism as an inherent oxymoron in a neoliberal global economy. Traditional economic growth, measured by GDP, relies on the perpetual expansion of production and resource consumption, which appears fundamentally irreconcilable with the physical limits of the biosphere. Critics argue that 'green growth' strategies, such as carbon offsets and efficiency gains, merely postpone ecological collapse while maintaining the inequitable status quo. Furthermore, the global South often bears the brunt of environmental degradation caused by the consumption patterns of the North, leading to calls for 'climate justice.' Achieving true sustainability may require moving beyond growth-centric paradigms toward 'steady-state' or 'post-growth' economies focused on human well-being within planetary boundaries.",
            transcript: "The concept of 'sustainable development' often faces criticism as an inherent oxymoron in a neoliberal global economy. Traditional economic growth, measured by GDP, relies on the perpetual expansion of production and resource consumption, which appears fundamentally irreconcilable with the physical limits of the biosphere. Critics argue that 'green growth' strategies, such as carbon offsets and efficiency gains, merely postpone ecological collapse while maintaining the inequitable status quo. Furthermore, the global South often bears the brunt of environmental degradation caused by the consumption patterns of the North, leading to calls for 'climate justice.' Achieving true sustainability may require moving beyond growth-centric paradigms toward 'steady-state' or 'post-growth' economies focused on human well-being within planetary boundaries.",
            questions: [
                {
                    question: "Why is 'sustainable development' called an oxymoron by some?",
                    options: ["It's too long", "Growth relies on expansion but the biosphere has limits", "Nobody knows what it means", "It only applies to small farms"],
                    correct: 1,
                    explanation: "In the passage: 'relies on the perpetual expansion... fundamentally irreconcilable with the physical limits of the biosphere.'",
                },
                {
                    question: "What are 'green growth' strategies accused of by critics?",
                    options: ["Being too expensive", "Solving all problems", "Merely postponing ecological collapse", "Promoting unfair laws"],
                    correct: 2,
                    explanation: "In the passage: 'merely postpone ecological collapse while maintaining the inequitable status quo.'",
                },
                {
                    question: "What is mentioned as a specific green growth strategy?",
                    options: ["Taxes", "Carbon offsets and efficiency gains", "Building more cities", "Advertising"],
                    correct: 1,
                    explanation: "In the passage: ''green growth' strategies, such as carbon offsets and efficiency gains...'",
                },
                {
                    question: "What does the term 'climate justice' address?",
                    options: ["Criminals in space", "Inequitable distribution of environmental degradation", "Lower temperatures", "Justice for polar bears"],
                    correct: 1,
                    explanation: "In the passage: 'South often bears the brunt... leading to calls for 'climate justice.''",
                },
                {
                    question: "Toward what type of economy does true sustainability potentially move?",
                    options: ["Hyper-growth", "Steady-state or post-growth", "Barter-based", "Fully automated"],
                    correct: 1,
                    explanation: "In the passage: 'moving toward 'steady-state' or 'post-growth' economies...' ",
                },
                {
                    question: "What is the primary focus of these alternative economies?",
                    options: ["Maximum GDP", "Human well-being within planetary boundaries", "Military superiority", "Technological dominance"],
                    correct: 1,
                    explanation: "In the passage: 'focused on human well-being within planetary boundaries.'",
                },
            ],
        },
        {
            id: "c2-comp-7",
            title: "The Sociology of Hyper-Connectivity",
            level: "C2",
            content: "In our era of hyper-connectivity, the boundary between the public and private spheres has become increasingly porous, leading to a phenomenon sociologists call 'context collapse.' On social media platforms, diverse social audiences—family, friends, colleagues, and strangers—are merged into a single, undifferentiated 'public,' making it difficult for individuals to manage their self-presentation effectively. This lack of context can lead to misunderstandings, the viral spread of private information, and the rise of 'online shaming.' Furthermore, the constant demand for 'curated' self-performances can lead to psychological strain and a sense of inauthenticity. The challenge for modern society is to redefine privacy and digital etiquette in a world where every action is potentially visible and archived forever.",
            transcript: "In our era of hyper-connectivity, the boundary between the public and private spheres has become increasingly porous, leading to a phenomenon sociologists call 'context collapse.' On social media platforms, diverse social audiences—family, friends, colleagues, and strangers—are merged into a single, undifferentiated 'public,' making it difficult for individuals to manage their self-presentation effectively. This lack of context can lead to misunderstandings, the viral spread of private information, and the rise of 'online shaming.' Furthermore, the constant demand for 'curated' self-performances can lead to psychological strain and a sense of inauthenticity. The challenge for modern society is to redefine privacy and digital etiquette in a world where every action is potentially visible and archived forever.",
            questions: [
                {
                    question: "What is 'context collapse' as described in the text?",
                    options: ["The end of the internet", "The merging of diverse social audiences into one public", "A server failure", "Losing one's keys"],
                    correct: 1,
                    explanation: "In the passage: 'diverse social audiences... are merged into a single, undifferentiated 'public'...'",
                },
                {
                    question: "What makes self-presentation difficult online?",
                    options: ["Slow upload speeds", "Context collapse and merged audiences", "Lack of profile pictures", "High cost of laptops"],
                    correct: 1,
                    explanation: "Merging audiences into one 'public' makes managing self-presentation difficult for different groups.",
                },
                {
                    question: "What is mentioned as a negative social outcome of this loss of context?",
                    options: ["Happiness", "Online shaming", "More friends", "Faster communication"],
                    correct: 1,
                    explanation: "In the passage: 'can lead to misunderstandings... and the rise of 'online shaming.''",
                },
                {
                    question: "What is a psychological consequence of hyper-connectivity?",
                    options: ["Better sleep", "Psychological strain and inauthenticity", "High intelligence", "Calmness"],
                    correct: 1,
                    explanation: "In the passage: 'can lead to psychological strain and a sense of inauthenticity.'",
                },
                {
                    question: "What are 'curated' self-performances?",
                    options: ["Professional acting", "Social media posts designed for a specific image", "Art exhibitions", "Cooking shows"],
                    correct: 1,
                    explanation: "Refers to the filtered and selective way people present their lives online.",
                },
                {
                    question: "What is the primary challenge for modern society according to the text?",
                    options: ["Building faster satellites", "Redefining privacy and digital etiquette", "Banning social media", "Deleting the internet"],
                    correct: 1,
                    explanation: "In the passage: 'redefine privacy and digital etiquette in a world where every action is visible...'",
                },
            ],
        },
        {
            id: "c2-comp-8",
            title: "Quantum Entanglement and Reality",
            level: "C2",
            content: "Quantum entanglement, famously described by Einstein as 'spooky action at a distance,' is a phenomenon where particles become interlinked such that the state of one instantaneously influences the state of another, regardless of the physical distance separating them. This violates the principle of 'locality'—the idea that objects are only influenced by their immediate surroundings. Experimental verification of entanglement, such as Bell's theorem, suggests that the universe might be fundamentally 'non-local.' This has profound implications for our understanding of reality, suggesting that the universe is not a collection of isolated objects but an interconnected web of dependencies. Harnessing entanglement is the cornerstone of emerging technologies like quantum cryptography and quantum teleportation, which promise to revolutionize information transfer in the twenty-first century.",
            transcript: "Quantum entanglement, famously described by Einstein as 'spooky action at a distance,' is a phenomenon where particles become interlinked such that the state of one instantaneously influences the state of another, regardless of the physical distance separating them. This violates the principle of 'locality'—the idea that objects are only influenced by their immediate surroundings. Experimental verification of entanglement, such as Bell's theorem, suggests that the universe might be fundamentally 'non-local.' This has profound implications for our understanding of reality, suggesting that the universe is not a collection of isolated objects but an interconnected web of dependencies. Harnessing entanglement is the cornerstone of emerging technologies like quantum cryptography and quantum teleportation, which promise to revolutionize information transfer in the twenty-first century.",
            questions: [
                {
                    question: "What was Einstein's description of quantum entanglement?",
                    options: ["A simple puzzle", "Spooky action at a distance", "The key to everything", "A mathematical error"],
                    correct: 1,
                    explanation: "In the passage: 'famously described by Einstein as 'spooky action at a distance...'",
                },
                {
                    question: "What happens when two particles are entangled?",
                    options: ["They move apart", "The state of one instantaneously influences the other", "They explode", "They disappear"],
                    correct: 1,
                    explanation: "In the passage: 'state of one instantaneously influences the state of another...'",
                },
                {
                    question: "What principle does entanglement violate?",
                    options: ["Gravity", "Locality", "Evolution", "Thermodynamics"],
                    correct: 1,
                    explanation: "In the passage: 'This violates the principle of 'locality'—the idea that objects are only influenced by their immediate surroundings.'",
                },
                {
                    question: "What is suggested by the experimental verification of entanglement?",
                    options: ["The universe is local", "The universe is fundamentally non-local", "Science is wrong", "The universe is empty"],
                    correct: 1,
                    explanation: "In the passage: 'suggests that the universe might be fundamentally 'non-local.''",
                },
                {
                    question: "What is the new view of the universe proposed?",
                    options: ["A huge machine", "An interconnected web of dependencies", "Isolated objects in space", "A liquid state"],
                    correct: 1,
                    explanation: "In the passage: 'suggesting that the universe is not a collection of isolated objects but an interconnected web...'",
                },
                {
                    question: "Which two emerging technologies rely on entanglement?",
                    options: ["Steam engines and radio", "AI and VR", "Quantum cryptography and quantum teleportation", "Laser and Radar"],
                    correct: 2,
                    explanation: "In the passage: 'cornerstone of emerging technologies like quantum cryptography and quantum teleportation...'",
                },
            ],
        },
        {
            id: "c2-comp-9",
            title: "The Philosophy of Existentialism",
            level: "C2",
            content: "Existentialism is a 20th-century philosophical movement that emphasizes individual freedom, responsibility, and the inherent lack of objective meaning in the universe. Jean-Paul Sartre, a key figure, famously declared that 'existence precedes essence,' suggesting that humans are not born with a predefined purpose but must create their own through their choices and actions. This freedom, however, is often experienced as 'angst' or 'nausea'—the dizzying realization of our total responsibility in an indifferent world. Albert Camus explored this through the concept of 'the absurd'—the conflict between the human desire for meaning and the 'silent' universe. For existentialists, the ultimate challenge is to live 'authentically'—acknowledging the absurdity of existence while still asserting one's own values and meaning.",
            transcript: "Existentialism is a 20th-century philosophical movement that emphasizes individual freedom, responsibility, and the inherent lack of objective meaning in the universe. Jean-Paul Sartre, a key figure, famously declared that 'existence precedes essence,' suggesting that humans are not born with a predefined purpose but must create their own through their choices and actions. This freedom, however, is often experienced as 'angst' or 'nausea'—the dizzying realization of our total responsibility in an indifferent world. Albert Camus explored this through the concept of 'the absurd'—the conflict between the human desire for meaning and the 'silent' universe. For existentialists, the ultimate challenge is to live 'authentically'—acknowledging the absurdity of existence while still asserting one's own values and meaning.",
            questions: [
                {
                    question: "What are three key emphases of existentialism?",
                    options: ["Laws, rules, and fate", "Freedom, responsibility, and lack of objective meaning", "Science, logic, and math", "Wealth, power, and fame"],
                    correct: 1,
                    explanation: "In the passage: 'emphasizes individual freedom, responsibility, and the inherent lack of objective meaning...'",
                },
                {
                    question: "What does Sartre's 'existence precedes essence' mean?",
                    options: ["We are born with a purpose", "We must create our own purpose through choices", "God defines our lives", "Nature is the boss"],
                    correct: 1,
                    explanation: "In the passage: 'humans are not born with a predefined purpose but must create their own...'",
                },
                {
                    question: "How is existential freedom often experienced?",
                    options: ["As pure joy", "As 'angst' or 'nausea'", "As confusion", "As a dream"],
                    correct: 1,
                    explanation: "In the passage: 'experienced as 'angst' or 'nausea'—the dizzying realization...'",
                },
                {
                    question: "How did Albert Camus define 'the absurd'?",
                    options: ["A joke", "Conflict between human desire for meaning and a silent universe", "Scientific error", "Political lie"],
                    correct: 1,
                    explanation: "In the passage: 'the conflict between the human desire for meaning and the 'silent' universe.'",
                },
                {
                    question: "What is the goal of living 'authentically'?",
                    options: ["Avoiding all choices", "Acknowledging absurdity while asserting one's own values", "Following the crowd", "Finding the secret meaning of the universe"],
                    correct: 1,
                    explanation: "In the passage: 'acknowledging the absurdity of existence while still asserting one's own values and meaning.'",
                },
                {
                    question: "What realization leads to 'angst' in the text?",
                    options: ["Total responsibility in an indifferent world", "Running out of food", "Dying soon", "Being unknown"],
                    correct: 0,
                    explanation: "In the passage: 'dizzying realization of our total responsibility in an indifferent world.'",
                },
            ],
        },
        {
            id: "c2-comp-10",
            title: "The Evolution of Language and Cognition",
            level: "C2",
            content: "The co-evolution of language and the human brain remains a central puzzle in evolutionary biology and linguistics. The 'recursion' hypothesis, championed by Noam Chomsky, suggests that the capacity for infinite nested structures is the unique, 'biological' core of human language. However, some evolutionary psychologists argue that language emerged primarily as a social tool, driven by the need for complex cooperation and 'theory of mind'—the ability to attribute mental states to others. This social interaction may have provided the selection pressure for larger brains and more sophisticated vocal control. Recent research in 'neuro-linguistics' is uncovering the specific neural networks involved, suggesting that language is not a single 'module' but a highly distributed process that repurposed existing brain structures for new, symbolic functions.",
            transcript: "The co-evolution of language and the human brain remains a central puzzle in evolutionary biology and linguistics. The 'recursion' hypothesis, championed by Noam Chomsky, suggests that the capacity for infinite nested structures is the unique, 'biological' core of human language. However, some evolutionary psychologists argue that language emerged primarily as a social tool, driven by the need for complex cooperation and 'theory of mind'—the ability to attribute mental states to others. This social interaction may have provided the selection pressure for larger brains and more sophisticated vocal control. Recent research in 'neuro-linguistics' is uncovering the specific neural networks involved, suggesting that language is not a single 'module' but a highly distributed process that repurposed existing brain structures for new, symbolic functions.",
            questions: [
                {
                    question: "What is the 'recursion' hypothesis in linguistics?",
                    options: ["Language is learned by copying", "The capacity for infinite nested structures", "Language is a series of sounds", "Words have no meaning"],
                    correct: 1,
                    explanation: "In the passage: 'suggests that the capacity for infinite nested structures is the unique... core...'",
                },
                {
                    question: "Who is the major proponent of recursion mentioned?",
                    options: ["Sartre", "Chomsky", "Darwin", "Skinner"],
                    correct: 1,
                    explanation: "In the passage: 'championed by Noam Chomsky.'",
                },
                {
                    question: "What do evolutionary psychologists argue was the driver for language?",
                    options: ["Reading books", "The need for complex cooperation and 'theory of mind'", "Finding more fruit", "Climate change"],
                    correct: 1,
                    explanation: "In the passage: 'driven by the need for complex cooperation and 'theory of mind'...' ",
                },
                {
                    question: "What is 'theory of mind'?",
                    options: ["A scientific paper", "The ability to attribute mental states to others", "A style of meditation", "Learning new facts"],
                    correct: 1,
                    explanation: "In the passage: ''theory of mind'—the ability to attribute mental states to others.'",
                },
                {
                    question: "How does 'neuro-linguistics' describe the nature of language?",
                    options: ["A single module in the brain", "A highly distributed process repurposing existing structures", "A physical muscle", "A type of electrical signal"],
                    correct: 1,
                    explanation: "In the passage: 'not a single 'module' but a highly distributed process that repurposed existing brain structures...'",
                },
                {
                    question: "What selection pressure is mentioned as a possible cause for larger brains?",
                    options: ["Extreme cold", "Social interaction", "Predators", "Lack of water"],
                    correct: 1,
                    explanation: "In the passage: 'This social interaction may have provided the selection pressure for larger brains...'",
                },
            ],
        }
    ],
};
